<?php
// Die eigenen Workbench-Texte des Images-Moduls, in seine Fills gemischt,
// solange das Modul aktiv ist (siehe text() des Panels) - dieselben
// Schlüssel und dieselbe Form wie text/<locale>.php der Workbench
return [
	'[[/_admin/nav/images]]'				=> 'Bilder',
	'[[/_admin/images/label/back]]'				=> 'Zurück zur Liste',
	'[[/_admin/images/msg/pending]]'				=> 'Wird hochgeladen …',
	'[[/_admin/images/msg/saved]]'					=> 'Gespeichert.',
	'[[/_admin/images/error/save]]'				=> 'Speichern fehlgeschlagen.',
	'[[/_admin/images/error/load]]'				=> 'Laden fehlgeschlagen.',
	'[[/_admin/images/label/remove]]'	=> 'Bild entfernen',
	'[[/_admin/images/confirm/remove]]'	=> 'Bild aus „%s“ entfernen? Es wird gelöscht, und die Website zeigt dort kein Bild, bis Du ein neues hochlädst.',
	'[[/_admin/images/msg/removed]]'	=> 'Bild entfernt.',
	'[[/_admin/images/error/remove]]'	=> 'Entfernen fehlgeschlagen.',
	'[[/_admin/images/msg/below-target]]'	=> 'Gespeichert – aber Dein Bild ist nur %s groß, kleiner als die Soll-Maße, und wurde hochskaliert. Es kann unscharf wirken.',
	'[[/_admin/images/label/alt]]'	=> 'Alt-Text (%s)',
	'[[/_admin/images/hint/alt]]'	=> 'Beschreibe kurz, was das Bild zeigt. Leer = dekorativ (alt=""), es sei denn, das Template gibt einen eigenen Alt-Text vor.',
	'[[/_admin/images/label/alt-save]]'	=> 'Alt-Texte speichern',
	'[[/_admin/images/msg/alt-saved]]'	=> 'Alt-Texte gespeichert.',
	'[[/_admin/images/error/alt]]'	=> 'Alt-Texte konnten nicht gespeichert werden.',
	'[[/_admin/images/label/usedon]]'	=> 'Verwendet auf: %s',
	'[[/_admin/images/msg/unused]]'	=> 'Nirgends eingebunden: Keine Seite verwendet diesen Bildplatz, ein Bild hier erscheint nicht auf der Website.',
	'[[/_admin/nav/slots]]'							=> 'Bildplätze',
	'[[/_admin/slots/empty]]'						=> 'Noch keine Bildplätze. Lege unten einen an oder durchsuche die Templates.',
	'[[/_admin/slots/empty/images]]'		=> 'Noch keine Bildplätze. Lege zuerst welche an.',
	'[[/_admin/slots/label/noimage]]'		=> 'kein Bild',
	'[[/_admin/slots/label/unused]]'	=> 'nirgends eingebunden',
	'[[/_admin/slots/label/templates]]'	=> 'Templates: %s',
	'[[/_admin/slots/label/new]]'				=> 'Neuer Bildplatz',
	'[[/_admin/slots/label/scan]]'			=> 'Templates nach fehlenden Bildplätzen durchsuchen',
	'[[/_admin/slots/label/uri]]'				=> 'Uri (z. B. /template/page-home/hero/image)',
	'[[/_admin/slots/label/width]]'			=> 'Breite (px)',
	'[[/_admin/slots/label/height]]'		=> 'Höhe (px)',
	'[[/_admin/slots/label/delete]]'		=> 'Bildplatz löschen',
	'[[/_admin/slots/label/scan-create]]'	=> 'Die nicht ignorierten Bildplätze anlegen',
	'[[/_admin/slots/scan/none]]'				=> 'Keine fehlenden Bildplätze. Jedes lokal referenzierte Bild der Templates hat bereits einen Platz.',
	'[[/_admin/slots/scan/created-failed]]'	=> '%d angelegt. Fehlgeschlagen: %s',
	'[[/_admin/slots/confirm/delete]]'	=> 'Bildplatz „%s“ wirklich löschen? Ein hochgeladenes Bild geht mit ihm verloren.',
	'[[/_admin/dashboard/label/slots]]'	=> 'Fehlende Bildplätze',
];
