<?php
// The Images module's own workbench strings, merged into its fills while
// the module is active (see the panel's text()) - same keys and shape the
// workbench's own text/<locale>.php has
return [
	'[[/_admin/nav/images]]'				=> 'Images',
	'[[/_admin/images/label/back]]'				=> 'Back to list',
	'[[/_admin/images/msg/pending]]'				=> 'Uploading …',
	'[[/_admin/images/msg/saved]]'					=> 'Saved.',
	'[[/_admin/images/error/save]]'				=> 'Save failed.',
	'[[/_admin/images/error/load]]'				=> 'Failed to load.',
	'[[/_admin/images/label/remove]]'	=> 'Remove image',
	'[[/_admin/images/confirm/remove]]'	=> 'Remove the image from “%s”? It is deleted, and the website shows no image there until you upload a new one.',
	'[[/_admin/images/msg/removed]]'	=> 'Image removed.',
	'[[/_admin/images/error/remove]]'	=> 'Removing failed.',
	'[[/_admin/images/msg/below-target]]'	=> 'Saved – but your image is only %s, smaller than the target size, and was scaled up. It may look blurry.',
	'[[/_admin/images/label/alt]]'	=> 'Alt text (%s)',
	'[[/_admin/images/hint/alt]]'	=> 'Describe briefly what the image shows. Empty = decorative (alt=""), unless the template provides an alt text of its own.',
	'[[/_admin/images/label/alt-save]]'	=> 'Save alt texts',
	'[[/_admin/images/msg/alt-saved]]'	=> 'Alt texts saved.',
	'[[/_admin/images/error/alt]]'	=> 'Saving the alt texts failed.',
	'[[/_admin/images/label/usedon]]'	=> 'Used on: %s',
	'[[/_admin/images/msg/unused]]'	=> 'Not included anywhere: no page uses this image slot, so an image here does not appear on the website.',
	'[[/_admin/nav/slots]]'							=> 'Image Slots',
	'[[/_admin/slots/empty]]'						=> 'No image slots yet. Create one below or scan the templates.',
	'[[/_admin/slots/empty/images]]'		=> 'No image slots yet. Create some first.',
	'[[/_admin/slots/label/noimage]]'		=> 'no image',
	'[[/_admin/slots/label/unused]]'	=> 'not included anywhere',
	'[[/_admin/slots/label/templates]]'	=> 'Templates: %s',
	'[[/_admin/slots/label/new]]'				=> 'New image slot',
	'[[/_admin/slots/label/scan]]'			=> 'Scan templates for missing image slots',
	'[[/_admin/slots/label/uri]]'				=> 'Uri (eg. /template/page-home/hero/image)',
	'[[/_admin/slots/label/width]]'			=> 'Width (px)',
	'[[/_admin/slots/label/height]]'		=> 'Height (px)',
	'[[/_admin/slots/label/delete]]'		=> 'Delete slot',
	'[[/_admin/slots/label/scan-create]]'	=> 'Create the non-ignored slots',
	'[[/_admin/slots/scan/none]]'				=> 'No missing slots found. Every local image the templates reference is already backed by a slot.',
	'[[/_admin/slots/scan/created-failed]]'	=> '%d created. Failed: %s',
	'[[/_admin/slots/confirm/delete]]'	=> 'Really delete image slot “%s”? Any uploaded image is lost with it.',
	'[[/_admin/dashboard/label/slots]]'	=> 'Missing image slots',
];
