<?php
// Die eigenen Workbench-Texte des Design-Moduls, in seine Fills gemischt,
// solange das Modul aktiv ist (siehe text() des Panels) - dieselben
// Schlüssel und dieselbe Form wie text/<locale>.php der Workbench.
// templates/panel.tpl und assets/design.js lesen sie
return [
	'[[/_admin/nav/design]]'						=> 'Design',
	'[[/_admin/design/label/appearance]]'	=> 'Erscheinungsbild',
	'[[/_admin/design/label/theme]]'		=> 'Theme',
	'[[/_admin/design/label/header]]'		=> 'Header',
	'[[/_admin/design/label/footer]]'		=> 'Footer',
	'[[/_admin/design/label/apply-theme]]'	=> 'Theme anwenden',
	'[[/_admin/design/label/save-design]]'	=> 'Design speichern',
	'[[/_admin/design/label/apply-header]]'	=> 'Header anwenden',
	'[[/_admin/design/label/apply-footer]]'	=> 'Footer anwenden',
	'[[/_admin/design/label/active]]'		=> 'Aktiv',
	'[[/_admin/design/label/preview]]'	=> 'Vorschau %s',
	'[[/_admin/design/label/settings]]'	=> 'Design-Einstellungen',
	'[[/_admin/design/label/colour]]'		=> 'Farbe',
	'[[/_admin/design/label/raster]]'		=> 'Raster',
	'[[/_admin/design/label/primary]]'	=> 'Primär',
	'[[/_admin/design/label/secondary]]'	=> 'Sekundär',
	'[[/_admin/design/hint/secondary]]'	=> 'übersteuert Harmonie',
	'[[/_admin/design/label/mode]]'			=> 'Vorschaumodus',
	'[[/_admin/design/label/light]]'		=> 'Hell',
	'[[/_admin/design/label/dark]]'			=> 'Dunkel',
	'[[/_admin/design/label/reset]]'		=> 'Zurück zu den Werten des Themes',
	'[[/_admin/design/label/example]]'	=> 'Live-Vorschau des aktuellen Designs',
	'[[/_admin/design/label/header-variant]]'	=> 'Header-Variante',
	'[[/_admin/design/label/footer-variant]]'	=> 'Footer-Variante',
	'[[/_admin/design/label/header-preview]]'	=> 'Header-Vorschau',
	'[[/_admin/design/label/footer-preview]]'	=> 'Footer-Vorschau',
	'[[/_admin/design/empty/theme]]'		=> 'Es sind keine Theme-Varianten verfügbar.',
	'[[/_admin/design/empty/header]]'		=> 'Es sind keine Header-Varianten verfügbar.',
	'[[/_admin/design/empty/footer]]'		=> 'Es sind keine Footer-Varianten verfügbar.',
	'[[/_admin/design/empty/library]]'	=> 'Das Verzeichnis /_admin/install/library muss vorhanden sein.',
	'[[/_admin/design/error/colour]]'		=> 'Eine Farbe braucht ein vollständiges #rrggbb – diese bleibt aus dem Design heraus, bis es eines ist.',
	'[[/_admin/design/msg/reverted]]'		=> 'Zurück zu den eigenen Werten des Themes.',
	'[[/_admin/design/confirm/theme]]'	=> 'Ein Theme anzuwenden ersetzt das Design durch das, was es vorgibt. Die ungespeicherten Design-Änderungen verwerfen?',
	'[[/_admin/design/msg/applying-theme]]'	=> 'Die vollständige Theme-Basis wird angewendet …',
	'[[/_admin/design/msg/theme-applied]]'	=> 'Theme angewendet. Design, Header und Footer nutzen jetzt seine empfohlene Basis.',
	'[[/_admin/design/msg/writing]]'		=> 'Design wird geschrieben …',
	'[[/_admin/design/msg/written]]'		=> 'Design geschrieben.',
	'[[/_admin/design/msg/applying-frame]]'	=> '%s wird angewendet …',
	'[[/_admin/design/msg/frame-applied]]'	=> '%s angewendet.',
	'[[/_admin/design/msg/dirty]]'			=> '1 ungespeicherte Design-Änderung',
	'[[/_admin/design/msg/dirty-plural]]'	=> '%d ungespeicherte Design-Änderungen',

	// Die Markierung, die Nino.adminUi.fieldChange() neben einen Regler setzt, dessen
	// gespeicherter Wert vom angezeigten abweicht - das geteilte Bauteil hat keine
	// eigenen Worte
	'[[/_admin/design/label/auto]]'		=> 'automatisch',
	'[[/_admin/design/label/saved]]'		=> 'gespeichert: %s',
	'[[/_admin/design/label/unset]]'		=> 'keine',

	// Die Einstellungen des Design-Panels, ein Fill je Regler. Das Schema selbst
	// (\Nino\Modules\Design\Tokens::KNOBS) bleibt englisch: Der Einrichtungs-
	// assistent rendert dieselben Regler und erreicht gar keine Fills, also ist es
	// der Rückfall, auf den das Panel zurückgreift (siehe _knobText() in design.js)
	'[[/_admin/design/knob/harmony/label]]'     	=> 'Harmonie',
	'[[/_admin/design/knob/harmony/note]]'      	=> 'wo die zweite Farbe sitzt',
	'[[/_admin/design/knob/harmony/hint]]'      	=> 'Wo die zweite Markenfarbe im Farbkreis relativ zur ersten sitzt – die vier klassischen Harmonien. Eine eigene Sekundärfarbe hat Vorrang.',
	'[[/_admin/design/knob/harmony/step/1]]'    	=> 'Monochrom',
	'[[/_admin/design/knob/harmony/step/2]]'    	=> 'Analog',
	'[[/_admin/design/knob/harmony/step/3]]'    	=> 'Triadisch',
	'[[/_admin/design/knob/harmony/step/4]]'    	=> 'Komplementär',
	'[[/_admin/design/knob/temperature/label]]' 	=> 'Temperatur',
	'[[/_admin/design/knob/temperature/note]]'  	=> 'wohin die Grautöne neigen',
	'[[/_admin/design/knob/temperature/hint]]'  	=> 'Wohin die Grautöne neigen. Bei Marke tragen sie eine Spur des Markentons selbst, bei Neutral gar keine Farbe.',
	'[[/_admin/design/knob/temperature/step/1]]'	=> 'Neutral',
	'[[/_admin/design/knob/temperature/step/2]]'	=> 'Kühl',
	'[[/_admin/design/knob/temperature/step/3]]'	=> 'Marke',
	'[[/_admin/design/knob/temperature/step/4]]'	=> 'Warm',
	'[[/_admin/design/knob/saturation/label]]'  	=> 'Sättigung',
	'[[/_admin/design/knob/saturation/note]]'   	=> 'wie viel Farbe',
	'[[/_admin/design/knob/saturation/hint]]'   	=> 'Wie viel Farbe jede Fläche trägt – Seitengrund, Rahmen und Links eingeschlossen, nicht nur die Marke.',
	'[[/_admin/design/knob/saturation/step/1]]' 	=> 'Gedämpft',
	'[[/_admin/design/knob/saturation/step/2]]' 	=> 'Standard',
	'[[/_admin/design/knob/saturation/step/3]]' 	=> 'Kräftig',
	'[[/_admin/design/knob/contrast/label]]'    	=> 'Kontrast',
	'[[/_admin/design/knob/contrast/note]]'     	=> 'wie hart der Text liest',
	'[[/_admin/design/knob/contrast/hint]]'     	=> 'Wie hart die Schrift liest. Jede Position erfüllt WCAG AA – der Regler entscheidet, wie weit darüber die Farbe liegt.',
	'[[/_admin/design/knob/contrast/step/1]]'   	=> 'Weich',
	'[[/_admin/design/knob/contrast/step/2]]'   	=> 'Standard',
	'[[/_admin/design/knob/contrast/step/3]]'   	=> 'Stark',
	'[[/_admin/design/knob/depth/label]]'       	=> 'Tiefe',
	'[[/_admin/design/knob/depth/note]]'        	=> 'Trennung der Flächen',
	'[[/_admin/design/knob/depth/hint]]'        	=> 'Wie weit sich eine Fläche von der Seite abhebt – Zweitfläche, Rahmen und Schatten bewegen sich gemeinsam.',
	'[[/_admin/design/knob/depth/step/1]]'      	=> 'Flach',
	'[[/_admin/design/knob/depth/step/2]]'      	=> 'Standard',
	'[[/_admin/design/knob/depth/step/3]]'      	=> 'Erhaben',
	'[[/_admin/design/knob/scale/label]]'       	=> 'Größe',
	'[[/_admin/design/knob/scale/note]]'        	=> 'alles auf einmal',
	'[[/_admin/design/knob/scale/hint]]'        	=> 'Die Grundgröße, in der jede andere Größe gemessen wird – sie bewegt Schrift, Abstände und Radien gemeinsam.',
	'[[/_admin/design/knob/scale/step/1]]'      	=> 'Klein',
	'[[/_admin/design/knob/scale/step/2]]'      	=> 'Standard',
	'[[/_admin/design/knob/scale/step/3]]'      	=> 'Groß',
	'[[/_admin/design/knob/volume/label]]'      	=> 'Überschriften',
	'[[/_admin/design/knob/volume/note]]'       	=> 'wie weit sie wachsen',
	'[[/_admin/design/knob/volume/hint]]'       	=> 'Wie weit sich die Schriftskala auffächert. Der Fließtext bewegt sich nie – eine Skala wächst am oberen Ende.',
	'[[/_admin/design/knob/volume/step/1]]'     	=> 'Ruhig',
	'[[/_admin/design/knob/volume/step/2]]'     	=> 'Standard',
	'[[/_admin/design/knob/volume/step/3]]'     	=> 'Kräftig',
	'[[/_admin/design/knob/spacing/label]]'     	=> 'Abstände',
	'[[/_admin/design/knob/spacing/note]]'      	=> 'Lücken und Zeilenhöhe',
	'[[/_admin/design/knob/spacing/hint]]'      	=> 'Die Lücken zwischen den Dingen und die Zeilenhöhe, die dazugehört.',
	'[[/_admin/design/knob/spacing/step/1]]'    	=> 'Eng',
	'[[/_admin/design/knob/spacing/step/2]]'    	=> 'Standard',
	'[[/_admin/design/knob/spacing/step/3]]'    	=> 'Luftig',
	'[[/_admin/design/knob/shaping/label]]'     	=> 'Ecken',
	'[[/_admin/design/knob/shaping/note]]'      	=> 'wie rund',
	'[[/_admin/design/knob/shaping/hint]]'      	=> 'Eckenradien, von der harten Kante bis zur Pille.',
	'[[/_admin/design/knob/shaping/step/1]]'    	=> 'Scharf',
	'[[/_admin/design/knob/shaping/step/2]]'    	=> 'Standard',
	'[[/_admin/design/knob/shaping/step/3]]'    	=> 'Rund',
	'[[/_admin/design/knob/measure/label]]'     	=> 'Breite',
	'[[/_admin/design/knob/measure/note]]'      	=> 'wie breit der Inhalt läuft',
	'[[/_admin/design/knob/measure/hint]]'      	=> 'Wie breit der Inhalt laufen darf, bevor das Layout aufhört zu wachsen.',
	'[[/_admin/design/knob/measure/step/1]]'    	=> 'Schmal',
	'[[/_admin/design/knob/measure/step/2]]'    	=> 'Standard',
	'[[/_admin/design/knob/measure/step/3]]'    	=> 'Weit',
];
