<?php
// The Design module's own workbench strings, merged into its fills
// while the module is active (see the panel's text()) - same keys and
// shape the workbench's own text/<locale>.php has. templates/panel.tpl
// and assets/design.js read them
return [
	'[[/_admin/nav/design]]'						=> 'Design',
	'[[/_admin/design/label/appearance]]'	=> 'Appearance',
	'[[/_admin/design/label/theme]]'		=> 'Theme',
	'[[/_admin/design/label/header]]'		=> 'Header',
	'[[/_admin/design/label/footer]]'		=> 'Footer',
	'[[/_admin/design/label/apply-theme]]'	=> 'Apply Theme',
	'[[/_admin/design/label/save-design]]'	=> 'Save Design',
	'[[/_admin/design/label/apply-header]]'	=> 'Apply Header',
	'[[/_admin/design/label/apply-footer]]'	=> 'Apply Footer',
	'[[/_admin/design/label/active]]'		=> 'Active',
	'[[/_admin/design/label/preview]]'	=> '%s preview',
	'[[/_admin/design/label/settings]]'	=> 'Design settings',
	'[[/_admin/design/label/colour]]'		=> 'Colour',
	'[[/_admin/design/label/raster]]'		=> 'Raster',
	'[[/_admin/design/label/primary]]'	=> 'Primary',
	'[[/_admin/design/label/secondary]]'	=> 'Secondary',
	'[[/_admin/design/hint/secondary]]'	=> 'overrides Harmony',
	'[[/_admin/design/label/mode]]'			=> 'Preview mode',
	'[[/_admin/design/label/light]]'		=> 'Light',
	'[[/_admin/design/label/dark]]'			=> 'Dark',
	'[[/_admin/design/label/reset]]'		=> 'Back to the theme’s values',
	'[[/_admin/design/label/example]]'	=> 'Live preview of the current design',
	'[[/_admin/design/label/header-variant]]'	=> 'Header variant',
	'[[/_admin/design/label/footer-variant]]'	=> 'Footer variant',
	'[[/_admin/design/label/header-preview]]'	=> 'Header preview',
	'[[/_admin/design/label/footer-preview]]'	=> 'Footer preview',
	'[[/_admin/design/empty/theme]]'		=> 'No theme variants are available.',
	'[[/_admin/design/empty/header]]'		=> 'No Header variants are available.',
	'[[/_admin/design/empty/footer]]'		=> 'No Footer variants are available.',
	'[[/_admin/design/empty/library]]'	=> 'The directory /_admin/install/library must exist.',
	'[[/_admin/design/error/colour]]'		=> 'A colour needs a full #rrggbb – this one is kept out of the design until it is.',
	'[[/_admin/design/msg/reverted]]'		=> 'Back to the theme’s own values.',
	'[[/_admin/design/confirm/theme]]'	=> 'Applying a Theme replaces the Design with the one it declares. Discard the unsaved design changes?',
	'[[/_admin/design/msg/applying-theme]]'	=> 'Applying the complete Theme baseline …',
	'[[/_admin/design/msg/theme-applied]]'	=> 'Theme applied. Design, Header and Footer now use its recommended baseline.',
	'[[/_admin/design/msg/writing]]'		=> 'Writing Design …',
	'[[/_admin/design/msg/written]]'		=> 'Design written.',
	'[[/_admin/design/msg/applying-frame]]'	=> 'Applying %s …',
	'[[/_admin/design/msg/frame-applied]]'	=> '%s applied.',
	'[[/_admin/design/msg/dirty]]'			=> '1 unsaved design change',
	'[[/_admin/design/msg/dirty-plural]]'	=> '%d unsaved design changes',

	// The mark Nino.adminUi.fieldChange() puts beside a knob whose stored value
	// differs from the one on screen - the shared control owns no words of its own
	'[[/_admin/design/label/auto]]'		=> 'auto',
	'[[/_admin/design/label/saved]]'		=> 'saved: %s',
	'[[/_admin/design/label/unset]]'		=> 'none',

	// The Design settings, one fill per knob. The schema itself
	// (\Nino\Modules\Design\Tokens::KNOBS) keeps its English: the setup wizard
	// renders the same knobs and reaches no fills at all, so it is the fallback
	// the panel falls back to (see design.js's _knobText())
	'[[/_admin/design/knob/harmony/label]]'     	=> 'Harmony',
	'[[/_admin/design/knob/harmony/note]]'      	=> 'where the second colour sits',
	'[[/_admin/design/knob/harmony/hint]]'      	=> 'Where the second brand colour sits on the wheel relative to the first - the four classical harmonies. A Secondary colour of your own overrides it.',
	'[[/_admin/design/knob/harmony/step/1]]'    	=> 'Monochrome',
	'[[/_admin/design/knob/harmony/step/2]]'    	=> 'Analogous',
	'[[/_admin/design/knob/harmony/step/3]]'    	=> 'Triadic',
	'[[/_admin/design/knob/harmony/step/4]]'    	=> 'Complementary',
	'[[/_admin/design/knob/temperature/label]]' 	=> 'Temperature',
	'[[/_admin/design/knob/temperature/note]]'  	=> 'how the greys lean',
	'[[/_admin/design/knob/temperature/hint]]'  	=> 'Which way the greys lean. At Brand they carry a trace of the brand hue itself; at Neutral they carry no colour at all.',
	'[[/_admin/design/knob/temperature/step/1]]'	=> 'Neutral',
	'[[/_admin/design/knob/temperature/step/2]]'	=> 'Cool',
	'[[/_admin/design/knob/temperature/step/3]]'	=> 'Brand',
	'[[/_admin/design/knob/temperature/step/4]]'	=> 'Warm',
	'[[/_admin/design/knob/saturation/label]]'  	=> 'Saturation',
	'[[/_admin/design/knob/saturation/note]]'   	=> 'how much colour',
	'[[/_admin/design/knob/saturation/hint]]'   	=> 'How much colour every surface carries - the page ground, the borders and the links included, not only the brand.',
	'[[/_admin/design/knob/saturation/step/1]]' 	=> 'Muted',
	'[[/_admin/design/knob/saturation/step/2]]' 	=> 'Standard',
	'[[/_admin/design/knob/saturation/step/3]]' 	=> 'Rich',
	'[[/_admin/design/knob/contrast/label]]'    	=> 'Contrast',
	'[[/_admin/design/knob/contrast/note]]'     	=> 'how hard text reads',
	'[[/_admin/design/knob/contrast/hint]]'     	=> 'How hard the type reads. Every position clears WCAG AA - the knob decides how far above it the ink sits.',
	'[[/_admin/design/knob/contrast/step/1]]'   	=> 'Soft',
	'[[/_admin/design/knob/contrast/step/2]]'   	=> 'Standard',
	'[[/_admin/design/knob/contrast/step/3]]'   	=> 'Strong',
	'[[/_admin/design/knob/depth/label]]'       	=> 'Depth',
	'[[/_admin/design/knob/depth/note]]'        	=> 'surface separation',
	'[[/_admin/design/knob/depth/hint]]'        	=> 'How far a panel separates from the page - the alternate surface, the borders and the shadows move together.',
	'[[/_admin/design/knob/depth/step/1]]'      	=> 'Flat',
	'[[/_admin/design/knob/depth/step/2]]'      	=> 'Standard',
	'[[/_admin/design/knob/depth/step/3]]'      	=> 'Raised',
	'[[/_admin/design/knob/scale/label]]'       	=> 'Size',
	'[[/_admin/design/knob/scale/note]]'        	=> 'everything at once',
	'[[/_admin/design/knob/scale/hint]]'        	=> 'The root size every other size is measured in, so it moves type, spacing and radii together.',
	'[[/_admin/design/knob/scale/step/1]]'      	=> 'Small',
	'[[/_admin/design/knob/scale/step/2]]'      	=> 'Standard',
	'[[/_admin/design/knob/scale/step/3]]'      	=> 'Large',
	'[[/_admin/design/knob/volume/label]]'      	=> 'Headings',
	'[[/_admin/design/knob/volume/note]]'       	=> 'how far they grow',
	'[[/_admin/design/knob/volume/hint]]'       	=> 'How far the type scale fans out. Body copy never moves - a scale grows at the display end.',
	'[[/_admin/design/knob/volume/step/1]]'     	=> 'Calm',
	'[[/_admin/design/knob/volume/step/2]]'     	=> 'Standard',
	'[[/_admin/design/knob/volume/step/3]]'     	=> 'Bold',
	'[[/_admin/design/knob/spacing/label]]'     	=> 'Spacing',
	'[[/_admin/design/knob/spacing/note]]'      	=> 'gaps and line height',
	'[[/_admin/design/knob/spacing/hint]]'      	=> 'The gaps between things, and the line height that belongs with them.',
	'[[/_admin/design/knob/spacing/step/1]]'    	=> 'Tight',
	'[[/_admin/design/knob/spacing/step/2]]'    	=> 'Standard',
	'[[/_admin/design/knob/spacing/step/3]]'    	=> 'Airy',
	'[[/_admin/design/knob/shaping/label]]'     	=> 'Corners',
	'[[/_admin/design/knob/shaping/note]]'      	=> 'how round',
	'[[/_admin/design/knob/shaping/hint]]'      	=> 'Corner radii, from a hard edge to a pill.',
	'[[/_admin/design/knob/shaping/step/1]]'    	=> 'Sharp',
	'[[/_admin/design/knob/shaping/step/2]]'    	=> 'Standard',
	'[[/_admin/design/knob/shaping/step/3]]'    	=> 'Round',
	'[[/_admin/design/knob/measure/label]]'     	=> 'Width',
	'[[/_admin/design/knob/measure/note]]'      	=> 'how wide content runs',
	'[[/_admin/design/knob/measure/hint]]'      	=> 'How wide the content may run before the layout stops growing.',
	'[[/_admin/design/knob/measure/step/1]]'    	=> 'Narrow',
	'[[/_admin/design/knob/measure/step/2]]'    	=> 'Standard',
	'[[/_admin/design/knob/measure/step/3]]'    	=> 'Wide',
];
