<?php
// Die eigenen Workbench-Texte des Features-Moduls, in seine Fills gemischt,
// solange das Modul aktiv ist (siehe text() des Panels) - dieselben
// Schlüssel und dieselbe Form wie text/<locale>.php der Workbench. Ein %s
// füllt das Skript - das Features-Verzeichnis, eine Version, eine Liste
// von Schlüsseln, ein Datum - oder, in einer Meldung, die das Panel
// selbst formuliert (siehe sein _say()), das Panel: den Grund des Kernels
return [
	'[[/_admin/nav/features]]'								=> 'Features',
	'[[/_admin/features/label/active]]'				=> 'Aktive Features',
	'[[/_admin/features/tab/available]]'			=> 'Verfügbar',
	'[[/_admin/features/label/filter]]'			=> 'Nach Namen filtern',
	'[[/_admin/features/label/category]]'			=> 'Kategorie',
	'[[/_admin/features/label/category-all]]'	=> 'Alle Kategorien',
	// Je eine pro \Nino\Features::CATEGORIES, dazu eine für ein Feature ohne
	// Angabe. Eine Kategorie, für die diese Workbench keine Zeile hat - ein
	// Feature aus einem späteren Katalog -, erscheint als der Slug, der sie
	// ist; der Filter gruppiert sie trotzdem
	'[[/_admin/features/category/content]]'		=> 'Inhalte',
	'[[/_admin/features/category/ui]]'				=> 'Darstellung',
	'[[/_admin/features/category/communication]]'	=> 'Kommunikation',
	'[[/_admin/features/category/marketing]]'	=> 'Marketing & Analyse',
	'[[/_admin/features/category/security]]'	=> 'Sicherheit & Datenschutz',
	'[[/_admin/features/category/system]]'		=> 'System & Betrieb',
	'[[/_admin/features/category/none]]'			=> 'Ohne Kategorie',
	'[[/_admin/features/hint/nomatch]]'			=> 'Auf diesem Tab passt nichts zum Filter.',
	'[[/_admin/features/tab/inactive]]'				=> 'Inaktiv',
	'[[/_admin/features/tab/active]]'					=> 'Aktiv',
	'[[/_admin/features/hint/empty]]'					=> 'Es sind keine Features installiert. Ein Feature ist ein Verzeichnis unter %s, mit einem feature.php-Manifest neben seiner Klasse.',
	'[[/_admin/features/hint/active-empty]]'	=> 'Kein Feature ist eingeschaltet.',
	'[[/_admin/features/label/version]]'			=> 'Version %s',
	'[[/_admin/features/label/installed]]'		=> 'installiert als %s',
	'[[/_admin/features/label/requires]]'			=> 'Benötigt: %s',
	'[[/_admin/features/label/settings]]'			=> 'Einstellungen',
	'[[/_admin/features/label/none]]'					=> '– keine –',
	'[[/_admin/features/label/activate]]'			=> 'Aktivieren',
	'[[/_admin/features/label/remove]]'				=> 'Entfernen',
	'[[/_admin/features/confirm/remove]]'			=> 'Das Verzeichnis von „%s“ entfernen? Seine Einstellungen, seine Dateien unter data/ und alles, was seine Install-Einheit ins Projekt kopiert hat, bleiben – wer das Feature zurückholt, findet sie wieder.',
	'[[/_admin/features/msg/removing]]'				=> 'Wird entfernt …',
	'[[/_admin/features/error/remove]]'				=> 'Das Verzeichnis konnte nicht entfernt werden.',
	'[[/_admin/features/msg/installed-with]]'	=> 'Installiert, zusammen mit dem, was es benötigt: %s.',
	'[[/_admin/features/label/deactivate]]'		=> 'Deaktivieren',
	'[[/_admin/features/label/update]]'				=> 'Auf %s aktualisieren',
	'[[/_admin/features/hint/secret-set]]'		=> 'Ein Wert ist gespeichert. Lass das Feld leer, um ihn zu behalten, oder gib einen neuen ein, um ihn zu ersetzen.',
	'[[/_admin/features/hint/secret-unset]]'	=> 'Noch nichts gespeichert.',
	'[[/_admin/features/hint/lines]]'					=> 'Ein Eintrag pro Zeile.',
	'[[/_admin/features/msg/activating]]'			=> 'Wird aktiviert …',
	'[[/_admin/features/msg/activated]]'			=> 'Aktiviert.',
	'[[/_admin/features/msg/deactivating]]'		=> 'Wird deaktiviert …',
	'[[/_admin/features/msg/deactivated]]'		=> 'Deaktiviert.',
	'[[/_admin/features/msg/updating]]'				=> 'Wird aktualisiert …',
	'[[/_admin/features/msg/updated]]'				=> 'Aktualisiert.',
	'[[/_admin/features/msg/reload]]'					=> 'Die Workbench lädt neu, damit die Navigation die Änderung zeigt …',
	'[[/_admin/features/error/activate]]'			=> 'Das Feature konnte nicht aktiviert werden.',
	'[[/_admin/features/error/deactivate]]'		=> 'Das Feature konnte nicht deaktiviert werden.',
	'[[/_admin/features/error/update]]'				=> 'Das Feature konnte nicht aktualisiert werden.',
	'[[/_admin/features/label/catalogue-refresh]]'	=> 'Katalog aktualisieren',
	'[[/_admin/features/label/catalogue-status]]'	=> 'Katalog vom %s',
	'[[/_admin/features/label/catalogue-unloaded]]'	=> 'noch nicht geladen',
	'[[/_admin/features/hint/catalogue-off]]'	=> 'Der Katalog ist ausgeschaltet: /nino/catalogue/url in der config.php ist leer. Ein Feature wird von Hand nach %s kopiert.',
	'[[/_admin/features/hint/available-unloaded]]'	=> 'Der Katalog wurde noch nicht geladen. Drücke Katalog aktualisieren, um zu sehen, was verfügbar ist.',
	'[[/_admin/features/hint/available-empty]]'	=> 'Alles, was der Katalog anbietet, ist bereits installiert und aktuell.',
	'[[/_admin/features/msg/catalogue-loading]]'	=> 'Katalog wird geladen …',
	'[[/_admin/features/hint/catalogue-readonly]]'	=> 'Der Webserver kann nicht nach %s schreiben, also wird von hier aus nichts installiert: lade ein Archiv herunter und entpacke es dort von Hand.',
	'[[/_admin/features/hint/catalogue-empty]]'	=> 'Der Katalog führt keine Features.',
	'[[/_admin/features/label/install]]'			=> 'Installieren',
	'[[/_admin/features/label/archive]]'			=> 'Archiv herunterladen',
	'[[/_admin/features/label/released]]'			=> 'veröffentlicht %s',
	'[[/_admin/features/label/nino]]'					=> 'Benötigt Nino %s',
	'[[/_admin/features/label/extensions]]'		=> 'Benötigt die PHP-Erweiterungen %s',
	'[[/_admin/features/msg/installing]]'			=> 'Wird installiert …',
	'[[/_admin/features/msg/installed]]'			=> 'Installiert.',
	'[[/_admin/features/error/install]]'			=> 'Das Feature konnte nicht installiert werden.',
	'[[/_admin/features/error/catalogue]]'		=> 'Der Katalog konnte nicht geladen werden.',
	'[[/_admin/features/error/catalogue-reason]]'	=> 'Der Katalog konnte nicht geladen werden: %s',
	'[[/_admin/features/error/catalogue-off]]'	=> 'Der Katalog ist ausgeschaltet: /nino/catalogue/url in der config.php ist leer.',
	'[[/_admin/features/error/catalogue-key]]'	=> 'Es ist kein Katalog-Schlüssel konfiguriert, also kann keinem Katalog vertraut werden.',
	'[[/_admin/features/error/update-after-install]]'	=> 'Die neuen Dateien sind an Ort und Stelle, aber das Update konnte nicht angewendet werden: %s',
];
