<?php
// The Features module's own workbench strings, merged into its fills while
// the module is active (see the panel's text()) - same keys and shape the
// workbench's own text/<locale>.php has. A %s is filled by the script - the
// features directory, a version, a list of keys, a date - or, in a message
// the panel phrases itself (see its _say()), by the panel: the kernel's
// reason
return [
	'[[/_admin/nav/features]]'								=> 'Features',
	'[[/_admin/features/label/active]]'				=> 'Active features',
	'[[/_admin/features/tab/available]]'			=> 'Available',
	'[[/_admin/features/label/filter]]'			=> 'Filter by name',
	'[[/_admin/features/hint/nomatch]]'			=> 'Nothing on this tab matches the filter.',
	'[[/_admin/features/tab/inactive]]'				=> 'Inactive',
	'[[/_admin/features/tab/active]]'					=> 'Active',
	'[[/_admin/features/hint/empty]]'					=> 'No features are installed. A feature is one directory under %s, with a feature.php manifest beside its class.',
	'[[/_admin/features/hint/active-empty]]'	=> 'No feature is switched on.',
	'[[/_admin/features/label/version]]'			=> 'Version %s',
	'[[/_admin/features/label/installed]]'		=> 'installed as %s',
	'[[/_admin/features/label/requires]]'			=> 'Requires: %s',
	'[[/_admin/features/label/settings]]'			=> 'Settings',
	'[[/_admin/features/label/none]]'					=> '– none –',
	'[[/_admin/features/label/activate]]'			=> 'Activate',
	'[[/_admin/features/label/deactivate]]'		=> 'Deactivate',
	'[[/_admin/features/label/update]]'				=> 'Update to %s',
	'[[/_admin/features/hint/secret-set]]'		=> 'A value is stored. Leave the field empty to keep it, or type a new one to replace it.',
	'[[/_admin/features/hint/secret-unset]]'	=> 'Nothing is stored yet.',
	'[[/_admin/features/hint/lines]]'					=> 'One entry per line.',
	'[[/_admin/features/msg/activating]]'			=> 'Activating …',
	'[[/_admin/features/msg/activated]]'			=> 'Activated.',
	'[[/_admin/features/msg/deactivating]]'		=> 'Deactivating …',
	'[[/_admin/features/msg/deactivated]]'		=> 'Deactivated.',
	'[[/_admin/features/msg/updating]]'				=> 'Updating …',
	'[[/_admin/features/msg/updated]]'				=> 'Updated.',
	'[[/_admin/features/msg/reload]]'					=> 'The workbench is reloading so its navigation shows the change …',
	'[[/_admin/features/error/activate]]'			=> 'The feature could not be activated.',
	'[[/_admin/features/error/deactivate]]'		=> 'The feature could not be deactivated.',
	'[[/_admin/features/error/update]]'				=> 'The feature could not be updated.',
	'[[/_admin/features/label/catalogue-refresh]]'	=> 'Refresh catalogue',
	'[[/_admin/features/label/catalogue-status]]'	=> 'Catalogue as of %s',
	'[[/_admin/features/label/catalogue-unloaded]]'	=> 'not loaded yet',
	'[[/_admin/features/hint/catalogue-off]]'	=> 'The catalogue is switched off: /nino/catalogue/url in config.php is empty. A feature is copied into %s by hand.',
	'[[/_admin/features/hint/available-unloaded]]'	=> 'The catalogue has not been loaded yet. Press Refresh catalogue to see what is available.',
	'[[/_admin/features/hint/available-empty]]'	=> 'Everything the catalogue offers is already installed, up to date.',
	'[[/_admin/features/msg/catalogue-loading]]'	=> 'Loading the catalogue …',
	'[[/_admin/features/hint/catalogue-readonly]]'	=> 'The web server cannot write to %s, so nothing is installed from here: download an archive and unpack it there by hand.',
	'[[/_admin/features/hint/catalogue-empty]]'	=> 'The catalogue lists no features.',
	'[[/_admin/features/label/install]]'			=> 'Install',
	'[[/_admin/features/label/archive]]'			=> 'Download the archive',
	'[[/_admin/features/label/released]]'			=> 'released %s',
	'[[/_admin/features/label/nino]]'					=> 'Requires Nino %s',
	'[[/_admin/features/label/extensions]]'		=> 'Requires the php extensions %s',
	'[[/_admin/features/msg/installing]]'			=> 'Installing …',
	'[[/_admin/features/msg/installed]]'			=> 'Installed.',
	'[[/_admin/features/error/install]]'			=> 'The feature could not be installed.',
	'[[/_admin/features/error/catalogue]]'		=> 'The catalogue could not be loaded.',
	'[[/_admin/features/error/catalogue-reason]]'	=> 'The catalogue could not be loaded: %s',
	'[[/_admin/features/error/catalogue-off]]'	=> 'The catalogue is switched off: /nino/catalogue/url in config.php is empty.',
	'[[/_admin/features/error/catalogue-key]]'	=> 'No catalogue key is configured, so no catalogue can be trusted.',
	'[[/_admin/features/error/update-after-install]]'	=> 'The new files are in place, but the update could not be applied: %s',
];
