<?php
// Die eigenen Workbench-Texte des Users-Moduls, in seine Fills gemischt,
// solange das Modul aktiv ist (siehe text() des Panels) - dieselben
// Schlüssel und dieselbe Form wie text/<locale>.php der Workbench
return [
	'[[/_admin/nav/user]]'					=> 'Nutzer',
	'[[/_admin/nav/roles]]'					=> 'Nutzerrollen',
	'[[/_admin/nav/lockout]]'				=> 'Anmeldeschutz',
	'[[/_admin/users/label/mail]]'					=> 'E-Mail-Adresse',
	'[[/_admin/users/label/newpw]]'				=> 'Neues Passwort (leer lassen, um es nicht zu ändern)',
	'[[/_admin/users/label/currentpw]]'		=> 'Aktuelles Passwort zur Bestätigung',
	'[[/_admin/users/label/you]]'					=> 'Sie',
	'[[/_admin/users/label/save]]'					=> 'Speichern',
	'[[/_admin/users/label/back]]'					=> 'Zurück zur Liste',
	'[[/_admin/users/label/logoutall]]'		=> 'Überall abmelden',
	'[[/_admin/users/label/permissions-manage]]' => 'Nutzer verwalten',
	'[[/_admin/users/label/norole]]'			=> 'Keine Rolle',
	'[[/_admin/users/label/fullaccess]]'	=> 'Vollzugriff',
	'[[/_admin/users/msg/pending]]'				=> 'Wird gespeichert …',
	'[[/_admin/users/msg/saved]]'					=> 'Gespeichert.',
	'[[/_admin/users/msg/loggedout]]'			=> 'Auf allen Geräten abgemeldet.',
	'[[/_admin/users/error/save]]'					=> 'Speichern fehlgeschlagen.',
	'[[/_admin/users/error/load]]'					=> 'Laden fehlgeschlagen.',
	'[[/_admin/users/confirm/logoutall]]'	=> 'Diesen Nutzer wirklich auf allen Geräten abmelden?',
	'[[/_admin/users/label/new]]'				=> 'Neuer Nutzer',
	'[[/_admin/users/label/create]]'		=> 'Nutzer anlegen',
	'[[/_admin/users/label/password]]'	=> 'Passwort (mindestens 8 Zeichen)',
	'[[/_admin/users/label/role]]'			=> 'Rolle',
	'[[/_admin/users/label/role-self]]'	=> 'Die eigene Rolle ändert ein anderer Verwalter.',
	'[[/_admin/users/label/delete]]'		=> 'Nutzer löschen',
	'[[/_admin/users/confirm/delete]]'	=> 'Diesen Nutzer wirklich löschen? Das lässt sich nicht rückgängig machen.',
	'[[/_admin/users/error/create]]'		=> 'Der Nutzer konnte nicht angelegt werden.',
	'[[/_admin/roles/label/new]]'				=> 'Neue Rolle',
	'[[/_admin/roles/label/create]]'		=> 'Rolle anlegen',
	'[[/_admin/roles/label/id]]'				=> 'Kennung',
	'[[/_admin/roles/label/id-hint]]'		=> 'Kleinbuchstaben, Ziffern und Bindestriche – der Name, unter dem die Rolle gespeichert wird, z. B. „editor“. Lässt sich später nicht ändern.',
	'[[/_admin/roles/label/name]]'			=> 'Name',
	'[[/_admin/roles/label/permissions]]'	=> 'Berechtigungen',
	'[[/_admin/roles/label/full]]'			=> 'Vollzugriff – jedes Panel, auch die künftiger Module',
	'[[/_admin/roles/label/full-hint]]'	=> 'Vollzugriff umfasst jede Berechtigung, auch die, die kein Panel anbietet – daneben gibt es nichts zu wählen.',
	'[[/_admin/roles/group/other]]'	=> 'Nicht angeboten',
	'[[/_admin/roles/perms/search]]'	=> 'Berechtigungen durchsuchen…',
	'[[/_admin/roles/perms/empty]]'	=> 'Noch keine Berechtigung – diese Rolle öffnet nichts.',
	'[[/_admin/roles/perms/nomatches]]'	=> 'Keine Berechtigung passt.',
	'[[/_admin/roles/perms/more]]'	=> '%d Treffer – Suche verfeinern.',
	'[[/_admin/roles/perms/custom-placeholder]]'	=> '/_admin/elements/services/update/title',
	'[[/_admin/roles/perms/custom-hint]]'	=> 'Für die feineren Rechte, die keine Liste anbieten kann, trage eine Berechtigung von Hand ein: eine Aktion oder ein einzelnes Feld, z. B. „/_admin/elements/services/insert“ oder „/_admin/text/update/page-home/*“. Ein „*“ als letztes Segment heißt „und alles darunter“.',
	'[[/_admin/roles/perms/custom-invalid]]'	=> 'Keine Berechtigung: Beginne mit „/“ und verwende zwischen den Schrägstrichen Buchstaben, Ziffern, „_“, „-“, „.“ und „*“.',
	'[[/_admin/roles/perms/custom-full]]'	=> '„/*“ ist Vollzugriff – der Schalter am Kopf dieses Kastens.',
	'[[/_admin/roles/label/users]]'			=> 'Konten mit dieser Rolle',
	'[[/_admin/roles/label/save]]'			=> 'Speichern',
	'[[/_admin/roles/label/delete]]'		=> 'Rolle löschen',
	'[[/_admin/roles/label/delete-hint]]'	=> 'Eine Rolle, die Konten halten, lässt sich nicht löschen – gib ihnen zuerst eine andere.',
	'[[/_admin/roles/label/back]]'			=> 'Zurück zur Liste',
	'[[/_admin/roles/msg/pending]]'			=> 'Wird gespeichert …',
	'[[/_admin/roles/msg/saved]]'				=> 'Gespeichert.',
	'[[/_admin/roles/error/load]]'			=> 'Laden fehlgeschlagen.',
	'[[/_admin/roles/error/save]]'			=> 'Speichern fehlgeschlagen.',
	'[[/_admin/roles/confirm/delete]]'	=> 'Diese Rolle wirklich löschen?',
	'[[/_admin/roles/empty]]'						=> 'Noch keine Rollen.',
	'[[/_admin/dashboard/label/users]]'	=> 'Nutzer',
	'[[/_admin/lockout/intro]]'					=> 'Die Drossel vor der Anmeldung: Nach so vielen Fehlversuchen wird ein Konto so lange gesperrt. Derselbe Zähler läuft je IP, mit dem zehnfachen Limit.',
	'[[/_admin/lockout/label/maxtries]]'	=> 'Fehlversuche bis zur Sperre',
	'[[/_admin/lockout/hint/maxtries]]'	=> 'Je Konto gezählt. Der Zähler je IP löst beim Zehnfachen aus, damit eine Person, die sich vertippt, nicht alle hinter demselben Anschluss aussperrt.',
	'[[/_admin/lockout/label/cooldown]]'	=> 'Dauer der Sperre',
	'[[/_admin/lockout/hint/cooldown]]'	=> 'Wie lange ein gesperrtes Konto oder eine gesperrte IP gesperrt bleibt.',
];
