<?php
// The Users module's own workbench strings, merged into its fills while
// the module is active (see the panel's text()) - same keys and shape the
// workbench's own text/<locale>.php has
return [
	'[[/_admin/nav/user]]'					=> 'Users',
	'[[/_admin/nav/roles]]'					=> 'User roles',
	'[[/_admin/nav/lockout]]'				=> 'Login protection',
	'[[/_admin/users/label/mail]]'					=> 'Email address',
	'[[/_admin/users/label/newpw]]'				=> 'New password (leave blank to keep it unchanged)',
	'[[/_admin/users/label/currentpw]]'		=> 'Current password to confirm',
	'[[/_admin/users/label/you]]'					=> 'you',
	'[[/_admin/users/label/save]]'					=> 'Save',
	'[[/_admin/users/label/back]]'					=> 'Back to list',
	'[[/_admin/users/label/logoutall]]'		=> 'Log out everywhere',
	'[[/_admin/users/label/permissions-manage]]' => 'Manage users',
	'[[/_admin/users/label/norole]]'			=> 'No role',
	'[[/_admin/users/label/fullaccess]]'	=> 'Full access',
	'[[/_admin/users/msg/pending]]'				=> 'Saving …',
	'[[/_admin/users/msg/saved]]'					=> 'Saved.',
	'[[/_admin/users/msg/loggedout]]'			=> 'Logged out on all devices.',
	'[[/_admin/users/error/save]]'					=> 'Save failed.',
	'[[/_admin/users/error/load]]'					=> 'Failed to load.',
	'[[/_admin/users/confirm/logoutall]]'	=> 'Really log this user out on all devices?',
	'[[/_admin/users/label/new]]'				=> 'New user',
	'[[/_admin/users/label/create]]'		=> 'Create user',
	'[[/_admin/users/label/password]]'	=> 'Password (at least 8 characters)',
	'[[/_admin/users/label/role]]'			=> 'Role',
	'[[/_admin/users/label/role-self]]'	=> 'Your own role is changed by another manager.',
	'[[/_admin/users/label/delete]]'		=> 'Delete user',
	'[[/_admin/users/confirm/delete]]'	=> 'Really delete this user? This cannot be undone.',
	'[[/_admin/users/error/create]]'		=> 'Could not create the user.',
	'[[/_admin/roles/label/new]]'				=> 'New role',
	'[[/_admin/roles/label/create]]'		=> 'Create role',
	'[[/_admin/roles/label/id]]'				=> 'Identifier',
	'[[/_admin/roles/label/id-hint]]'		=> 'Lowercase letters, digits and hyphens – the name the role is stored under, e.g. “editor”. Cannot be changed later.',
	'[[/_admin/roles/label/name]]'			=> 'Name',
	'[[/_admin/roles/label/permissions]]'	=> 'Permissions',
	'[[/_admin/roles/label/full]]'			=> 'Full access – every panel, including those of future modules',
	'[[/_admin/roles/label/full-hint]]'	=> 'Full access covers every permission there is, the ones no panel offers included – there is nothing to pick beside it.',
	'[[/_admin/roles/group/other]]'	=> 'Not offered',
	'[[/_admin/roles/perms/search]]'	=> 'Search permissions…',
	'[[/_admin/roles/perms/empty]]'	=> 'No permission yet – this role opens nothing.',
	'[[/_admin/roles/perms/nomatches]]'	=> 'No permission matches.',
	'[[/_admin/roles/perms/more]]'	=> '%d matches – refine the search.',
	'[[/_admin/roles/perms/custom-placeholder]]'	=> '/_admin/elements/services/update/title',
	'[[/_admin/roles/perms/custom-hint]]'	=> 'Add a permission by hand for the finer ones no list can offer: an action or a single field, e.g. “/_admin/elements/services/insert” or “/_admin/text/update/page-home/*”. A “*” as the last segment means “and everything below”.',
	'[[/_admin/roles/perms/custom-invalid]]'	=> 'Not a permission: start with “/” and use letters, digits, “_”, “-”, “.” and “*” between the slashes.',
	'[[/_admin/roles/perms/custom-full]]'	=> '“/*” is full access – the switch at the top of this box.',
	'[[/_admin/roles/label/users]]'			=> 'Accounts with this role',
	'[[/_admin/roles/label/save]]'			=> 'Save',
	'[[/_admin/roles/label/delete]]'		=> 'Delete role',
	'[[/_admin/roles/label/delete-hint]]'	=> 'A role accounts hold cannot be deleted – give them another one first.',
	'[[/_admin/roles/label/back]]'			=> 'Back to list',
	'[[/_admin/roles/msg/pending]]'			=> 'Saving …',
	'[[/_admin/roles/msg/saved]]'				=> 'Saved.',
	'[[/_admin/roles/error/load]]'			=> 'Failed to load.',
	'[[/_admin/roles/error/save]]'			=> 'Save failed.',
	'[[/_admin/roles/confirm/delete]]'	=> 'Really delete this role?',
	'[[/_admin/roles/empty]]'						=> 'No roles yet.',
	'[[/_admin/dashboard/label/users]]'	=> 'Users',
	'[[/_admin/lockout/intro]]'					=> 'The throttle that sits in front of the login: after this many failed attempts an account is locked for this long. The same counter runs per ip, at ten times the limit.',
	'[[/_admin/lockout/label/maxtries]]'	=> 'Failed logins before lockout',
	'[[/_admin/lockout/hint/maxtries]]'	=> 'Counted per account. The per-ip bucket trips at ten times this, so one person mistyping cannot lock out everyone behind the same connection.',
	'[[/_admin/lockout/label/cooldown]]'	=> 'Lockout duration',
	'[[/_admin/lockout/hint/cooldown]]'	=> 'How long a locked account or ip stays locked.',
];
