<?php
// Die eigenen Workbench-Texte des Dashboard-Moduls, in seine Fills gemischt,
// solange das Modul aktiv ist (siehe text() des Panels) - dieselben
// Schlüssel und dieselbe Form wie text/<locale>.php der Workbench
return [
	'[[/_admin/nav/dashboard]]'			=> 'Dashboard',
	'[[/_admin/dashboard/error/load]]'			=> 'Laden fehlgeschlagen.',
	'[[/_admin/dashboard/label/lastbackup]]' => 'Letztes Backup',
	'[[/_admin/dashboard/label/elements]]'	=> 'Elemente nach Typ',
	'[[/_admin/dashboard/label/activity]]'	=> 'Letzte Aktivität',
	'[[/_admin/dashboard/label/all]]'				=> 'Alle anzeigen',
	'[[/_admin/dashboard/empty/elements]]'	=> 'Noch keine Element-Typen angelegt.',
	'[[/_admin/dashboard/empty/activity]]'	=> 'Noch keine Einträge.',
	'[[/_admin/dashboard/notice/mail]]'	=> 'Der Mailversand scheitert seit %s (Fehlversuche: %s). Prüfe mail() auf dem Server, die Einstellungen des Mailers oder die Empfängeradresse.',
	'[[/_admin/dashboard/notice/untranslated]]'	=> 'Noch nicht übersetzte Texte (%s) in %s.',
	'[[/_admin/dashboard/notice/legal-unknown]]'	=> 'Für die Angabe %s im Abschnitt „%s“ (%s) gibt es keinen Wert. Lege ihn unter Texte an oder nimm die Angabe aus dem Abschnitt.',
	'[[/_admin/dashboard/notice/legal-empty]]'	=> 'Die Angabe %s im Abschnitt „%s“ (%s) ist leer. Trage unter Texte einen Wert ein.',
	'[[/_admin/dashboard/notice/legal-ignored]]'	=> 'Die Angabe %s im Abschnitt „%s“ (%s) wird nie ersetzt: Erlaubt sind nur Schlüssel mit vier Teilen unter /project/company/ und /project/website/general/.',
	'[[/_admin/dashboard/notice/legal-translation]]'	=> 'Der Abschnitt „%s“ hat in %s weder Überschrift noch Text. Bis zur Übersetzung zeigt die Seite die Fassung der nativen Sprache.',
	'[[/_admin/dashboard/notice/legal-nothing]]'	=> 'Der Elementtyp „%s“ fehlt oder hat keinen sichtbaren Abschnitt. Ist er gelöscht, kopiere die Datei %s zurück nach private/elements/.',
	'[[/_admin/dashboard/notice/legal-route]]'	=> 'Rechtsseite „%s“ (%s): Der Pfad %s in /nino/legal/paths ist ungültig oder gehört schon einer anderen Route. Trage in der config.php einen eigenen, freien Pfad ein.',
	'[[/_admin/dashboard/notice/legal-route-derived]]'	=> 'Rechtsseite „%s“ (%s): Für diese Sprache steht in /nino/legal/paths kein Pfad, die Seite ist deshalb unter %s erreichbar. Willst Du einen anderen, trage ihn in der config.php ein.',
	'[[/_admin/dashboard/notice/legal-route-none]]'	=> 'Rechtsseite „%s“ (%s): Diese Sprache hat keine Route, denn in /nino/legal/paths steht kein Pfad für sie, und der abgeleitete (%s) fehlt oder ist belegt. Trage in der config.php einen eigenen, freien Pfad ein.',
	'[[/_admin/dashboard/notice/legal-route-stored]]'	=> 'Die gespeicherte Route %s trägt die Element-URI der Rechtsseite „%s“, die dem Modul gehört. Gib ihr eine eigene Element-URI oder entferne sie unter Routen.',
	'[[/_admin/dashboard/notice/legal-nav]]'	=> '„%s“ fehlt in %s in jedem Menü der Website. Nimm die Seite unter Navigationen in die Navigation „legal“ auf und gib ihr unter Routen in jeder Sprache einen Namen.',
	'[[/_admin/dashboard/notice/legal-feature]]'	=> 'Das Feature „%s“ ist abgeschaltet, die Datenschutzerklärung beschreibt es aber noch: %s. Blende diese Abschnitte unter Elements › Datenschutzerklärung aus, wenn sie nicht mehr zutreffen.',
	'[[/_admin/dashboard/notice/legal-undescribed]]'	=> 'Das Feature „%s“ ist aktiv, aber die Datenschutzerklärung hat keinen sichtbaren Abschnitt dazu. Blende ihn unter Elements › Datenschutzerklärung wieder ein oder beschreibe es dort selbst.',
	'[[/_admin/dashboard/notice/legal-more]]'	=> '… und %s weitere Hinweise zu den Rechtstexten.',
	'[[/_admin/dashboard/notice/open]]'	=> 'Öffnen',
];
