<?php
// Die eigenen Workbench-Texte des Routes-Moduls, in seine Fills gemischt,
// solange das Modul aktiv ist (siehe text() des Panels) - dieselben
// Schlüssel und dieselbe Form wie text/<locale>.php der Workbench
return [
	'[[/_admin/nav/routes]]'						=> 'Routen',
	'[[/_admin/routes/empty]]'					=> 'Noch keine Routen. Lege unten eine an.',
	'[[/_admin/routes/label/moveup]]'		=> 'Nach oben – ordnet auch die Navigationen um',
	'[[/_admin/routes/label/movedown]]'	=> 'Nach unten – ordnet auch die Navigationen um',
	'[[/_admin/routes/label/new]]'			=> 'Neue Route',
	'[[/_admin/routes/label/route]]'		=> 'Route',
	'[[/_admin/routes/label/uri]]'			=> 'Element-URI – eine stabile Kennung, nicht unbedingt der echte Pfad (siehe HTTP-URI)',
	'[[/_admin/routes/placeholder/uri]]'	=> 'Element-URI, z. B. „/ueber-uns“',
	'[[/_admin/routes/label/httpuri]]'	=> 'HTTP-URI – der echte, erreichbare Pfad im Browser',
	'[[/_admin/routes/placeholder/httpuri]]'	=> 'HTTP-URI, z. B. „/ueber-uns“',
	'[[/_admin/routes/label/template]]'	=> 'Template',
	'[[/_admin/routes/label/choose]]'		=> 'Template wählen …',
	'[[/_admin/routes/label/open]]'			=> 'Die Seite in einem neuen Tab öffnen',
	'[[/_admin/routes/label/runtime]]'	=> 'zur Laufzeit gewählt',
	'[[/_admin/routes/hint/runtime]]'		=> 'Diese Route wählt ihr Template je Anfrage: %s – bleibt, wie es ist.',
	'[[/_admin/routes/label/status]]'		=> 'Statuscode',
	'[[/_admin/routes/label/nav]]'			=> 'In der Navigation „%s“ zeigen',
	'[[/_admin/routes/label/content]]'	=> 'Inhalt',
	'[[/_admin/routes/hint/required]]'	=> 'Name und Titel sind in jeder Sprache Pflicht; die Beschreibung ist optional.',
	'[[/_admin/routes/error/required]]'	=> 'Bitte die markierten Felder ausfüllen: die URIs, ein Template sowie Name und Titel in jeder Sprache.',
	'[[/_admin/routes/aria/name]]'			=> 'Name (%s)',
	'[[/_admin/routes/aria/title]]'			=> 'HTML-Titel (%s)',
	'[[/_admin/routes/aria/description]]'	=> 'HTML-Beschreibung (%s)',
	'[[/_admin/routes/label/delete]]'		=> 'Route löschen',
	'[[/_admin/routes/runtime/title]]'	=> 'Feature-Routen',
	'[[/_admin/routes/runtime/hint]]'		=> 'Seiten, die ein Feature selbst ausliefert, etwa der Blog oder die Newsletter-Seite. Hier werden sie nicht gespeichert, und verschieben oder löschen lässt sich keine davon – aber Name, Titel und Beschreibung schreibst Du, in jeder Sprache.',
	'[[/_admin/routes/runtime/path]]'		=> 'Das Feature bestimmt diesen Pfad. Er wird hier angezeigt, nicht geändert.',
	'[[/_admin/routes/placeholder/name]]'	=> 'Name, z. B. „Über uns“',
	'[[/_admin/routes/placeholder/title]]'	=> 'HTML-Titel, z. B. „Über uns“',
	'[[/_admin/routes/placeholder/description]]'	=> 'HTML-Beschreibung',
	'[[/_admin/routes/confirm/delete-left]]'	=> 'Die Route unter „%s“ wirklich löschen? Es bleiben: %s.',
	'[[/_admin/routes/confirm/stays-texts]]'	=> 'die Texte %s',
	'[[/_admin/routes/confirm/stays-template]]'	=> 'das Template „%s“ (von keiner weiteren Route genutzt)',
	'[[/_admin/routes/confirm/stays-template-one]]'	=> 'das Template „%s“ (von einer weiteren Route genutzt)',
	'[[/_admin/routes/confirm/stays-template-shared]]'	=> 'das Template „%s“ (von %d weiteren Routen genutzt)',
	'[[/_admin/routes/confirm/stays-body]]'	=> 'der Body „%s“',
	'[[/_admin/dashboard/label/routes]]'	=> 'Routen',
	'[[/_admin/error/routes_invalid_uri]]'	=> 'Die Element-URI „%s“ ist ungültig.',
	'[[/_admin/error/routes_invalid_http_uri]]'	=> 'Die HTTP-URI „%s“ ist ungültig.',
	'[[/_admin/error/routes_reserved_http_uri]]'	=> 'Die HTTP-URI „%s“ ist von Nino reserviert. Wähle eine andere.',
	'[[/_admin/error/routes_duplicate_uri]]'	=> 'Eine andere Seite nutzt die Element-URI „%s“ schon.',
	'[[/_admin/error/routes_duplicate_http_uri]]'	=> 'Eine andere Seite nutzt die HTTP-URI „%s“ schon.',
	'[[/_admin/error/routes_http_uri_taken]]'	=> 'Die HTTP-URI „%s“ gehört schon zu einer anderen Route.',
	'[[/_admin/error/routes_unknown_template]]'	=> 'Das Template „%s“ gibt es nicht.',
	'[[/_admin/error/routes_missing_name]]'	=> 'Der Name für „%s“ fehlt.',
	'[[/_admin/error/routes_missing_title]]'	=> 'Der Titel für „%s“ fehlt.',
];
