<?php
// The Routes module's own workbench strings, merged into its fills while
// the module is active (see the panel's text()) - same keys and shape the
// workbench's own text/<locale>.php has
return [
	'[[/_admin/nav/routes]]'						=> 'Routes',
	'[[/_admin/routes/empty]]'					=> 'No routes yet. Create one below.',
	'[[/_admin/routes/label/moveup]]'		=> 'Move up – reorders the navigations too',
	'[[/_admin/routes/label/movedown]]'	=> 'Move down – reorders the navigations too',
	'[[/_admin/routes/label/new]]'			=> 'New route',
	'[[/_admin/routes/label/route]]'		=> 'Route',
	'[[/_admin/routes/label/uri]]'			=> 'Element URI – a stable identifier, not necessarily the real path (see Http URI)',
	'[[/_admin/routes/placeholder/uri]]'	=> 'Element URI, e.g. “/about”',
	'[[/_admin/routes/label/httpuri]]'	=> 'Http URI – the real, reachable browser path',
	'[[/_admin/routes/placeholder/httpuri]]'	=> 'Http URI, e.g. “/about”',
	'[[/_admin/routes/label/template]]'	=> 'Template',
	'[[/_admin/routes/label/runtime]]'	=> 'resolved at runtime',
	'[[/_admin/routes/hint/runtime]]'		=> 'This route picks its template per request: %s – left as it is.',
	'[[/_admin/routes/label/status]]'		=> 'Status code',
	'[[/_admin/routes/label/nav]]'			=> 'Show in the “%s” navigation',
	'[[/_admin/routes/label/content]]'	=> 'Content',
	'[[/_admin/routes/label/delete]]'		=> 'Delete route',
	'[[/_admin/routes/placeholder/name]]'	=> 'Name, e.g. “About”',
	'[[/_admin/routes/placeholder/title]]'	=> 'HTML title, e.g. “About us”',
	'[[/_admin/routes/placeholder/description]]'	=> 'HTML description',
	'[[/_admin/routes/confirm/delete]]'	=> 'Really delete the route at “%s”?',
	'[[/_admin/dashboard/label/routes]]'	=> 'Routes',
	'[[/_admin/error/routes_invalid_uri]]'	=> 'The Element URI “%s” is not valid.',
	'[[/_admin/error/routes_invalid_http_uri]]'	=> 'The Http URI “%s” is not valid.',
	'[[/_admin/error/routes_reserved_http_uri]]'	=> 'The Http URI “%s” is reserved by Nino. Choose another one.',
	'[[/_admin/error/routes_duplicate_uri]]'	=> 'Another page already uses the Element URI “%s”.',
	'[[/_admin/error/routes_duplicate_http_uri]]'	=> 'Another page already uses the Http URI “%s”.',
	'[[/_admin/error/routes_http_uri_taken]]'	=> 'The Http URI “%s” already belongs to another route.',
	'[[/_admin/error/routes_unknown_template]]'	=> 'The template “%s” does not exist.',
];
