<?php
// The Text module's own workbench strings, merged into its fills while
// the module is active (see the panel's text()) - same keys and shape the
// workbench's own text/<locale>.php has
return [
	'[[/_admin/nav/text]]'					=> 'Text',
	'[[/_admin/text/label/save]]'					=> 'Save',
	'[[/_admin/text/label/back]]'					=> 'Back to list',
	'[[/_admin/text/msg/pending]]'					=> 'Saving …',
	'[[/_admin/text/msg/saved]]'						=> 'Saved.',
	'[[/_admin/text/error/save]]'					=> 'Save failed.',
	'[[/_admin/text/error/load]]'					=> 'Failed to load.',
	'[[/_admin/nav/keys]]'							=> 'Text Keys',
	'[[/_admin/keys/empty]]'						=> 'No text keys yet. Create one below or scan the templates.',
	'[[/_admin/keys/label/scan]]'				=> 'Scan templates for missing keys',
	'[[/_admin/keys/label/new]]'				=> 'New text key',
	'[[/_admin/keys/label/blacklist]]'	=> 'Hidden from the Text panel',
	'[[/_admin/keys/label/perlocale]]'	=> 'Per language',
	'[[/_admin/keys/label/key]]'				=> 'Key (eg. /project/company/general/name)',
	'[[/_admin/keys/label/global-hint]]'	=> 'Global (one translation for all languages, instead of one per language)',
	'[[/_admin/keys/label/initial]]'		=> 'Initial value (for global, or as a starting point for every language)',
	'[[/_admin/keys/label/scan-value]]'	=> 'Starting value for every language',
	'[[/_admin/keys/label/scan-create]]'	=> 'Apply',
	'[[/_admin/keys/label/scan-ignore]]'	=> 'Ignore permanently',
	'[[/_admin/keys/scan/hint]]'			=> 'A key with a value is created in every language. A key left empty is passed over this once and comes back on the next scan. A key marked “Ignore permanently” is retired: it leaves this scan and the Text panel, and the Text Keys list is where you can bring it back.',
	'[[/_admin/keys/scan/result]]'		=> '%c key(s) created, %i permanently ignored, %s left for later.',
	'[[/_admin/keys/scan/none]]'				=> 'No missing keys found. Every key referenced in templates/*.tpl is already defined.',
	'[[/_admin/keys/scan/grammar]]'		=> 'Does not follow /<namespace>/<category>/<part>/<name>, so it cannot be created here. Rename it in the template.',
	'[[/_admin/keys/scan/system-routes]]'	=> 'A key of the system. The Routes panel writes it when a page with this Element URI is saved – and, for the name, title and description of a page a feature serves, under “Feature routes”.',
	'[[/_admin/keys/scan/system-language]]'	=> 'A key of the system. The Language panel writes it when the language is added.',
	'[[/_admin/keys/scan/system-none]]'	=> 'A key of the system that no panel writes. Change what the template reads.',
	'[[/_admin/keys/scan/hint-feature]]'	=> 'Normally belongs to the feature “%s”, whose install unit delivers it. If it is missing, the feature may not be active, or the key is misspelled.',
	'[[/_admin/keys/scan/hint-module]]'	=> 'Normally belongs to the module “%s”, whose install unit delivers it. If it is missing, the module may not be installed, or the key is misspelled.',
	'[[/_admin/keys/scan/also-title]]'	=> 'Also read by other templates',
	'[[/_admin/keys/scan/also-hint]]'		=> 'These keys belong to one template and another reads them as well. Nothing is changed. A word several templates read is meant to live in /template/common – move it there yourself if you want to share it.',
	'[[/_admin/keys/scan/also-line]]'		=> '%s – also read by %s',
	'[[/_admin/keys/confirm/delete]]'		=> 'Really delete text key “%s”? The value is lost in every language.',
	'[[/_admin/keys/label/format]]'		=> 'Format',
	'[[/_admin/keys/format/auto]]'		=> 'Automatic',
	'[[/_admin/keys/format/plain]]'		=> 'Plain text',
	'[[/_admin/keys/format/inline]]'		=> 'Formatted',
	'[[/_admin/keys/format/lines]]'		=> 'Line breaks',
	'[[/_admin/keys/format/blocks]]'		=> 'Paragraphs and lists',
	'[[/_admin/keys/label/limit]]'		=> 'Limit',
	'[[/_admin/keys/placeholder/limit]]'	=> 'Automatic',
	'[[/_admin/keys/label/apply]]'		=> 'Apply',
	'[[/_admin/keys/confirm/format]]'	=> 'Change the format of “%s” from “%s” to “%s”? Every stored text of the key is converted now, in every language, and cannot be converted back. %s',
	'[[/_admin/keys/convert/plain]]'	=> 'Formatting is removed; line breaks and the ends of paragraphs and list items stay as lines.',
	'[[/_admin/keys/convert/inline]]'	=> 'Paragraphs, lists and line breaks are removed; their text stays, joined with a space.',
	'[[/_admin/keys/convert/lines]]'	=> 'Paragraphs and lists become lines.',
	'[[/_admin/keys/error/save-partial]]'	=> 'Save failed for %s',
	'[[/_admin/dashboard/label/keys]]'	=> 'Missing text keys',
	'[[/_admin/error/keys_invalid]]'	=> 'The key “%s” is not valid. A key has four parts, /<namespace>/<category>/<part>/<name>, for example /project/company/general/name. The namespace is template, project, feature or module; every part is lowercase words joined by hyphens.',
	'[[/_admin/error/keys_exists]]'	=> 'The key “%s” already exists.',
	'[[/_admin/error/keys_system]]'	=> 'The key “%s” belongs to the system and is not renamed. Its value can be edited.',
	'[[/_admin/error/keys_format]]'	=> 'This format does not exist. Choose automatic, plain text, formatted, line breaks, or paragraphs and lists.',
	'[[/_admin/error/keys_limit]]'	=> 'The limit has to be a whole number from 1 to %d.',
	'[[/_admin/error/keys_limit_short]]'	=> 'The key already holds a text of %d characters. Shorten it first, or choose a higher limit.',
	'[[/_admin/text/scope/update]]'	=> 'Change values',
];
