<?php
return [
	'[[/_admin/login/label/user]]'	=> 'E-Mail',
	'[[/_admin/login/label/pw]]'		=> 'Passwort',
	'[[/_admin/login/label/submit]]'=> 'Anmelden',

	'[[/_admin/login/error/user]]'	=> 'E-Mail muss angegeben werden.',
	'[[/_admin/login/error/pw]]'		=> 'Passwort muss angegeben werden.',
	'[[/_admin/login/error/wrong]]'	=> 'Prüfen Sie Ihre Eingabe oder verständigen Sie den Administrator.',

	'[[/_admin/login/msg/welcome]]'	=> 'Geben Sie Ihre E-Mail und Ihre Passwort an:',
	'[[/_admin/login/msg/pending]]'	=> 'Eingabe wird geprüft.',

	'[[/_admin/user/logout]]'				=> 'Abmelden',
	'[[/_admin/user/theme]]'					=> 'Hell/Dunkel umschalten',
	'[[/_admin/user/settings]]'			=> 'Einstellungen',
	
	'[[/_admin/nav/dashboard]]'			=> 'Dashboard',
	'[[/_admin/nav/user]]'					=> 'Nutzer',
	'[[/_admin/nav/text]]'					=> 'Texte',
	'[[/_admin/nav/images]]'				=> 'Bilder',
	'[[/_admin/nav/elements]]'			=> 'Elemente',
	'[[/_admin/nav/submissions]]'		=> 'Anfragen',
	'[[/_admin/nav/newsletter]]'		=> 'Newsletter',
	'[[/_admin/nav/logs]]'					=> 'Log',

	'[[/_admin/elements/label/type]]'			=> 'Typ:',
	'[[/_admin/elements/label/add]]'				=> 'Neues Element',
	'[[/_admin/elements/label/uri]]'				=> 'Uri',
	'[[/_admin/elements/label/uri-hint]]'	=> 'Eindeutige Zeichenfolge (a-z, -, _) zur Identifikation, z. B. „offene-workshops“.',
	'[[/_admin/elements/label/global]]'		=> 'Global',
	'[[/_admin/elements/label/yes]]'				=> 'Ja',
	'[[/_admin/elements/label/no]]'				=> 'Nein',
	'[[/_admin/elements/label/image-savefirst]]'	=> 'Erst nach dem ersten Speichern verfügbar.',
	'[[/_admin/elements/label/image-target]]'		=> 'Soll-Maße:',
	'[[/_admin/elements/label/locale]]'		=> 'Übersetzung',
	'[[/_admin/elements/label/save]]'			=> 'Speichern',
	'[[/_admin/elements/label/delete]]'		=> 'Löschen',
	'[[/_admin/elements/label/back]]'			=> 'Zurück zu',
	'[[/_admin/elements/label/backtypes]]'	=> 'Zurück zur Übersicht',

	'[[/_admin/elements/msg/pending]]'			=> 'Wird gespeichert …',
	'[[/_admin/elements/msg/saved]]'				=> 'Gespeichert.',
	'[[/_admin/elements/error/uri]]'				=> 'Uri muss angegeben werden.',
	'[[/_admin/elements/error/save]]'			=> 'Speichern fehlgeschlagen.',
	'[[/_admin/elements/error/load]]'			=> 'Laden fehlgeschlagen.',
	'[[/_admin/elements/error/required]]'	=> 'Bitte füllen Sie alle Pflichtfelder aus:',
	'[[/_admin/elements/confirm/delete]]'	=> 'Dieses Element wirklich löschen?',

	// Multilocale Feld-Labels fürs Elements-Formular - je Typ + Modell-Key,
	// fehlende Übersetzungen fallen automatisch auf den rohen Key zurück
	'[[/_admin/elements/field/deals/title]]'					=> 'Titel',
	'[[/_admin/elements/field/deals/subtitle]]'			=> 'Untertitel',
	'[[/_admin/elements/field/deals/description]]'		=> 'Beschreibung',
	'[[/_admin/elements/field/deals/price_default]]'	=> 'Standardpreis',

	'[[/_admin/elements/field/partner/title]]'				=> 'Titel',
	'[[/_admin/elements/field/partner/description]]'	=> 'Beschreibung',
	'[[/_admin/elements/field/partner/url]]'					=> 'Webseite',

	'[[/_admin/elements/field/portfolio/title]]'			=> 'Titel',
	'[[/_admin/elements/field/portfolio/description]]'	=> 'Beschreibung',
	'[[/_admin/elements/field/portfolio/tasks]]'			=> 'Aufgaben',

	'[[/_admin/elements/field/pricelist/title]]'			=> 'Titel',
	'[[/_admin/elements/field/pricelist/price]]'			=> 'Preis',
	'[[/_admin/elements/field/pricelist/cat]]'				=> 'Kategorie',

	'[[/_admin/elements/field/services/title]]'			=> 'Titel',
	'[[/_admin/elements/field/services/subtitle]]'		=> 'Untertitel',
	'[[/_admin/elements/field/services/description]]'	=> 'Beschreibung',

	'[[/_admin/text/label/save]]'					=> 'Speichern',
	'[[/_admin/text/label/back]]'					=> 'Zurück zur Liste',

	'[[/_admin/text/msg/pending]]'					=> 'Wird gespeichert …',
	'[[/_admin/text/msg/saved]]'						=> 'Gespeichert.',
	'[[/_admin/text/error/save]]'					=> 'Speichern fehlgeschlagen.',
	'[[/_admin/text/error/load]]'					=> 'Laden fehlgeschlagen.',

	'[[/_admin/users/label/mail]]'					=> 'E-Mail-Adresse',
	'[[/_admin/users/label/newpw]]'				=> 'Neues Passwort (leer lassen, um es nicht zu ändern)',
	'[[/_admin/users/label/currentpw]]'		=> 'Aktuelles Passwort zur Bestätigung',
	'[[/_admin/users/label/you]]'					=> 'Sie',
	'[[/_admin/users/label/save]]'					=> 'Speichern',
	'[[/_admin/users/label/back]]'					=> 'Zurück zur Liste',
	'[[/_admin/users/label/logoutall]]'		=> 'Überall abmelden',
	'[[/_admin/users/label/permissions]]'	=> 'Berechtigungen',
	'[[/_admin/users/label/permissions-full]]' => 'Vollzugriff (alle Bereiche)',
	'[[/_admin/users/label/permissions-manage]]' => 'Nutzer verwalten',

	'[[/_admin/users/msg/pending]]'				=> 'Wird gespeichert …',
	'[[/_admin/users/msg/saved]]'					=> 'Gespeichert.',
	'[[/_admin/users/msg/loggedout]]'			=> 'Auf allen Geräten abgemeldet.',
	'[[/_admin/users/error/save]]'					=> 'Speichern fehlgeschlagen.',
	'[[/_admin/users/error/load]]'					=> 'Laden fehlgeschlagen.',
	'[[/_admin/users/confirm/logoutall]]'	=> 'Diesen Nutzer wirklich auf allen Geräten abmelden?',

	'[[/_admin/images/label/image]]'				=> 'Bild',
	'[[/_admin/images/label/back]]'				=> 'Zurück zur Liste',
	'[[/_admin/images/msg/pending]]'				=> 'Wird hochgeladen …',
	'[[/_admin/images/msg/saved]]'					=> 'Gespeichert.',
	'[[/_admin/images/error/save]]'				=> 'Speichern fehlgeschlagen.',
	'[[/_admin/images/error/load]]'				=> 'Laden fehlgeschlagen.',

	'[[/_admin/htmleditor/label/strong]]'	=> 'Fett',
	'[[/_admin/htmleditor/label/em]]'			=> 'Kursiv',
	'[[/_admin/htmleditor/label/span]]'		=> 'Hervorheben',
	'[[/_admin/htmleditor/label/a]]'				=> 'Link',
	'[[/_admin/htmleditor/label/linkplaceholder]]'	=> 'https://…',
	'[[/_admin/htmleditor/label/linkok]]'					=> 'Übernehmen',
	'[[/_admin/htmleditor/label/linkcancel]]'			=> 'Abbrechen',
];