<?php
// Die eigenen Worte der Workbench-Shell - und nur die. Jeder Bereich ist ein
// Modul unter _admin/Nino/Modules/ und bringt sein eigenes text/<locale>.php
// mit (siehe den Panel-Vertrag in Admin.php); hier bleibt, was die Shell
// selbst rendert - das Login-Formular, die Konto-Leiste, die Überschriften
// der Navigationsgruppen - dazu die beiden Sätze, auf die jedes Panel
// zugreifen darf: die Werkzeugleiste des Rich-Text-Editors
// (_admin/assets/html-editor.js) und /_admin/common/*, die Worte, die sonst
// in jedem Modul einzeln stünden.
return [
	'[[/_admin/login/label/user]]'	=> 'E-Mail',
	'[[/_admin/login/label/pw]]'		=> 'Passwort',
	'[[/_admin/login/label/submit]]'=> 'Anmelden',
	'[[/_admin/login/error/user]]'	=> 'E-Mail muss angegeben werden.',
	'[[/_admin/login/error/pw]]'		=> 'Passwort muss angegeben werden.',
	'[[/_admin/login/error/wrong]]'	=> 'Prüfe Deine Eingabe oder verständige den Administrator.',
	'[[/_admin/login/error/endpoint]]'=> 'Der Login-Endpunkt hat mit %s geantwortet - die Zugangsdaten wurden gar nicht geprüft. Das ist eine Serverkonfiguration, kein falsches Passwort.',
	'[[/_admin/login/error/csrf]]'	=> 'Diese Seite ist zu lange offen, ihr Sitzungs-Token gilt nicht mehr. Lade die Seite neu und melde Dich erneut an.',
	'[[/_admin/login/msg/welcome]]'	=> 'Gib Deine E-Mail und Dein Passwort an:',
	'[[/_admin/login/msg/pending]]'	=> 'Eingabe wird geprüft.',

	'[[/_admin/user/logout]]'				=> 'Abmelden',
	'[[/_admin/user/theme]]'					=> 'Hell/Dunkel umschalten',
	'[[/_admin/user/settings]]'			=> 'Einstellungen',
	'[[/_admin/user/rail]]'					=> 'Navigation ein- oder ausklappen',

	'[[/_admin/label/rail]]'			=> 'Navigation der Workbench',
	'[[/_admin/label/nav]]'			=> 'Bereiche der Workbench',
	'[[/_admin/label/language]]'	=> 'Sprache der Oberfläche',
	'[[/_admin/label/title]]'		=> 'Nino Workbench',
	'[[/_admin/nav/group/content]]'		=> 'Inhalt',
	'[[/_admin/nav/group/structure]]'	=> 'Struktur',
	'[[/_admin/nav/group/features]]'	=> 'Features',
	'[[/_admin/nav/group/system]]'		=> 'System',

	'[[/_admin/htmleditor/label/strong]]'	=> 'Fett',
	'[[/_admin/htmleditor/label/em]]'			=> 'Kursiv',
	'[[/_admin/htmleditor/label/span]]'		=> 'Hervorheben',
	'[[/_admin/htmleditor/label/code]]'		=> 'Code',
	'[[/_admin/htmleditor/label/a]]'				=> 'Link',
	'[[/_admin/htmleditor/label/linkplaceholder]]'	=> 'https://…',
	'[[/_admin/htmleditor/label/linkok]]'					=> 'Übernehmen',
	'[[/_admin/htmleditor/label/linkcancel]]'			=> 'Abbrechen',
	'[[/_admin/htmleditor/label/formatting]]'			=> 'Textformatierung',
	'[[/_admin/htmleditor/label/content]]'				=> 'Formatierter Text',

	'[[/_admin/common/label/image-target]]'		=> 'Soll-Maße:',
	'[[/_admin/common/label/locale]]'		=> 'Übersetzung',
	'[[/_admin/common/label/save]]'			=> 'Speichern',
	'[[/_admin/common/label/create]]'		=> 'Anlegen',
	'[[/_admin/common/label/delete]]'		=> 'Löschen',
	'[[/_admin/common/label/remove]]'		=> 'Entfernen',
	'[[/_admin/common/label/rename]]'		=> 'Umbenennen',
	'[[/_admin/common/label/add]]'			=> 'Hinzufügen',
	'[[/_admin/common/label/back]]'			=> 'Zurück zur Liste',
	'[[/_admin/common/label/moveup]]'		=> 'Nach oben',
	'[[/_admin/common/label/movedown]]'	=> 'Nach unten',
	'[[/_admin/common/label/ignore]]'		=> 'Ignorieren',
	'[[/_admin/common/label/uri]]'			=> 'Uri',
	'[[/_admin/common/label/label]]'		=> 'Bezeichnung',
	'[[/_admin/common/label/global]]'		=> 'Global',
	'[[/_admin/common/label/on]]'				=> 'an',
	'[[/_admin/common/label/off]]'			=> 'aus',
	// Die Namen hinter den drei Glyphen-Bedienelementen der geteilten
	// Tabelle - siehe Nino.adminUi.table(), die dafür kein eigenes Wort hat
	'[[/_admin/common/label/prevpage]]'	=> 'Vorherige Seite',
	'[[/_admin/common/label/nextpage]]'	=> 'Nächste Seite',
	'[[/_admin/common/label/perpage]]'	=> 'Zeilen pro Seite',
	'[[/_admin/common/msg/saving]]'			=> 'Wird gespeichert …',
	'[[/_admin/common/msg/saved]]'			=> 'Gespeichert.',
	'[[/_admin/common/msg/deleting]]'		=> 'Wird gelöscht …',
	'[[/_admin/common/msg/scanning]]'		=> 'Templates werden durchsucht …',
	'[[/_admin/common/msg/creating]]'		=> '%s wird angelegt (%d / %n) …',
	'[[/_admin/common/error/load]]'			=> 'Laden fehlgeschlagen.',
	'[[/_admin/common/error/save]]'			=> 'Speichern fehlgeschlagen.',
	'[[/_admin/common/error/delete]]'		=> 'Löschen fehlgeschlagen.',
	'[[/_admin/common/error/rename]]'		=> 'Umbenennen fehlgeschlagen.',
	'[[/_admin/common/error/scan]]'			=> 'Durchsuchen fehlgeschlagen.',
	'[[/_admin/common/error/request]]'	=> 'Anfrage fehlgeschlagen.',
	'[[/_admin/common/label/width]]'		=> 'Breite (px)',
	'[[/_admin/common/label/height]]'		=> 'Höhe (px)',
	'[[/_admin/common/label/restore]]'	=> 'Wiederherstellen',
	'[[/_admin/common/unit/seconds]]'		=> 'Sekunden',
	'[[/_admin/common/unit/decimal]]'	=> ',',
	'[[/_admin/common/msg/savedat]]'	=> 'Gespeichert um %s.',
	'[[/_admin/common/msg/dirty]]'	=> 'Ungespeicherte Änderungen',
	'[[/_admin/common/confirm/unsaved]]'	=> 'Du hast ungespeicherte Änderungen. Möchtest Du sie speichern, bevor es weitergeht?',
	'[[/_admin/common/label/discard]]'	=> 'Verwerfen',
	'[[/_admin/common/label/cancel]]'	=> 'Abbrechen',
	'[[/_admin/common/error/offline]]'	=> 'Keine Verbindung zum Server. Prüfe Deine Netzwerkverbindung und versuche es erneut.',
	'[[/_admin/common/hint/upload]]'	=> 'Bis zu %s MB und %s Megapixel.',
	'[[/_admin/common/session/title]]'	=> 'Sitzung abgelaufen',
	'[[/_admin/common/session/expired]]'	=> 'Deine Sitzung ist abgelaufen. Melde Dich erneut an – Deine Eingaben bleiben erhalten.',
	'[[/_admin/common/session/user]]'	=> 'E-Mail',
	'[[/_admin/common/session/pw]]'	=> 'Passwort',
	'[[/_admin/common/session/submit]]'	=> 'Anmelden',
	'[[/_admin/common/session/wrong]]'	=> 'Prüfe Deine Eingabe oder verständige den Administrator.',
	'[[/_admin/common/session/other]]'	=> 'In einem anderen Tab ist ein anderes Konto angemeldet. Lade die Seite neu, bevor Du weiterarbeitest.',
	'[[/_admin/common/session/other_title]]'	=> 'Anderes Konto',
	'[[/_admin/common/session/reload]]'	=> 'Seite neu laden',
	'[[/_admin/common/session/close]]'	=> 'Schließen',
	'[[/_admin/common/session/error]]'	=> 'Die Anmeldung hat nicht funktioniert (Status %s). Versuche es erneut oder lade die Seite neu.',
	// Die Fehlercodes, die jedes Panel kennen darf - was der Server als 'code' sendet (siehe \Nino\Http::fail()).
	// Ein Panel bringt seine eigenen Codes mit Präfix seines Kürzels in seinem text/ mit
	'[[/_admin/error/session]]'	=> 'Deine Sitzung ist abgelaufen.',
	'[[/_admin/error/csrf]]'	=> 'Das Sitzungs-Token dieser Seite gilt nicht mehr. Lade die Seite neu.',
	'[[/_admin/error/post_too_large]]'	=> 'Die Anfrage ist größer, als dieser Server annimmt (PHP-Limit für eine Anfrage: %s MB).',
	'[[/_admin/error/upload_too_large]]'	=> 'Die Datei ist größer, als dieser Server annimmt (PHP-Upload-Limit: %s MB).',
	'[[/_admin/error/upload_partial]]'	=> 'Die Datei kam nur teilweise an. Versuche es erneut.',
	'[[/_admin/error/upload_missing]]'	=> 'Es kam keine Datei an.',
	'[[/_admin/error/upload_server]]'	=> 'Der Server konnte den Upload nicht speichern. Prüfe sein temporäres Verzeichnis.',
	'[[/_admin/error/image_too_large]]'	=> 'Das Bild ist größer als %s MB.',
	'[[/_admin/error/image_type]]'	=> 'Diese Datei ist kein Bild, das Nino lesen kann. Nimm JPEG, PNG, WebP oder GIF.',
	'[[/_admin/error/image_too_many_pixels]]'	=> 'Das Bild hat mehr als %s Megapixel.',
	'[[/_admin/error/image_unreadable]]'	=> 'Das Bild konnte nicht verarbeitet werden. Versuche eine andere Datei.',
	'[[/_admin/error/int_range]]'	=> 'Gib eine ganze Zahl zwischen %s und %s ein.',
	'[[/_admin/error/bool]]'	=> 'Wähle an oder aus.',
	'[[/_admin/error/lines]]'	=> 'Gib einen Eintrag pro Zeile ein.',
	'[[/_admin/error/lines_ip]]'	=> 'Gib pro Zeile eine IP-Adresse oder einen CIDR-Bereich ein.',
	'[[/_admin/error/invalid_value]]'	=> 'Dieser Wert ist ungültig.',
	'[[/_admin/error/already_top]]'	=> 'Das steht schon ganz oben.',
	'[[/_admin/error/already_bottom]]'	=> 'Das steht schon ganz unten.',
	'[[/_admin/error/wrong_password]]'	=> 'Das aktuelle Passwort stimmt nicht.',
];
