<?php
// The workbench shell's own words - and only those. Every screen is a module
// under _admin/Nino/Modules/ and brings its own text/<locale>.php (see the
// panel contract in Admin.php); what is left here is what the shell itself
// renders - the login form, the account chrome, the navigation's group
// headings - plus the two sets any panel may reach for: the rich-text
// editor's toolbar (_admin/assets/html-editor.js) and /_admin/common/*, the
// words that would otherwise be written once per module.
return [
	'[[/_admin/login/label/user]]'	=> 'Email',
	'[[/_admin/login/label/pw]]'		=> 'Password',
	'[[/_admin/login/label/submit]]'=> 'Log in',
	'[[/_admin/login/error/user]]'	=> 'Email is required.',
	'[[/_admin/login/error/pw]]'		=> 'Password is required.',
	'[[/_admin/login/error/wrong]]'	=> 'Check your input or contact the administrator.',
	'[[/_admin/login/error/endpoint]]'=> 'The login endpoint answered %s - the credentials were never checked. That is a server configuration, not a wrong password.',
	'[[/_admin/login/error/csrf]]'	=> 'This page has been open too long and its session token is no longer valid. Reload the page and log in again.',
	'[[/_admin/login/msg/welcome]]'	=> 'Enter your email and password:',
	'[[/_admin/login/msg/pending]]'	=> 'Checking your input.',

	'[[/_admin/user/logout]]'				=> 'Log out',
	'[[/_admin/user/theme]]'					=> 'Toggle light/dark',
	'[[/_admin/user/settings]]'			=> 'Settings',
	'[[/_admin/user/rail]]'					=> 'Fold or unfold the navigation',

	'[[/_admin/label/rail]]'			=> 'Workbench navigation',
	'[[/_admin/label/nav]]'			=> 'Workbench sections',
	'[[/_admin/label/language]]'	=> 'Interface language',
	'[[/_admin/label/title]]'		=> 'Nino workbench',
	'[[/_admin/nav/group/content]]'		=> 'Content',
	'[[/_admin/nav/group/structure]]'	=> 'Structure',
	'[[/_admin/nav/group/features]]'	=> 'Features',
	'[[/_admin/nav/group/system]]'		=> 'System',

	'[[/_admin/htmleditor/label/strong]]'	=> 'Bold',
	'[[/_admin/htmleditor/label/em]]'			=> 'Italic',
	'[[/_admin/htmleditor/label/span]]'		=> 'Highlight',
	'[[/_admin/htmleditor/label/code]]'		=> 'Code',
	'[[/_admin/htmleditor/label/a]]'				=> 'Link',
	'[[/_admin/htmleditor/label/linkplaceholder]]'	=> 'https://…',
	'[[/_admin/htmleditor/label/linkok]]'					=> 'Apply',
	'[[/_admin/htmleditor/label/linkcancel]]'			=> 'Cancel',
	'[[/_admin/htmleditor/label/formatting]]'			=> 'Text formatting',
	'[[/_admin/htmleditor/label/content]]'				=> 'Formatted text',

	'[[/_admin/common/label/image-target]]'		=> 'Target size:',
	'[[/_admin/common/label/locale]]'		=> 'Translation',
	'[[/_admin/common/label/save]]'			=> 'Save',
	'[[/_admin/common/label/create]]'		=> 'Create',
	'[[/_admin/common/label/delete]]'		=> 'Delete',
	'[[/_admin/common/label/remove]]'		=> 'Remove',
	'[[/_admin/common/label/rename]]'		=> 'Rename',
	'[[/_admin/common/label/add]]'			=> 'Add',
	'[[/_admin/common/label/back]]'			=> 'Back to list',
	'[[/_admin/common/label/moveup]]'		=> 'Move up',
	'[[/_admin/common/label/movedown]]'	=> 'Move down',
	'[[/_admin/common/label/ignore]]'		=> 'Ignore',
	'[[/_admin/common/label/uri]]'			=> 'Uri',
	'[[/_admin/common/label/label]]'		=> 'Label',
	'[[/_admin/common/label/global]]'		=> 'Global',
	'[[/_admin/common/label/on]]'				=> 'on',
	'[[/_admin/common/label/off]]'			=> 'off',
	// The names behind the shared table's three glyph controls - see
	// Nino.adminUi.table(), which has no word of its own for them
	'[[/_admin/common/label/prevpage]]'	=> 'Previous page',
	'[[/_admin/common/label/nextpage]]'	=> 'Next page',
	'[[/_admin/common/label/perpage]]'	=> 'Rows per page',
	'[[/_admin/common/msg/saving]]'			=> 'Saving …',
	'[[/_admin/common/msg/saved]]'			=> 'Saved.',
	'[[/_admin/common/msg/deleting]]'		=> 'Deleting …',
	'[[/_admin/common/msg/scanning]]'		=> 'Scanning …',
	'[[/_admin/common/msg/creating]]'		=> 'Creating %s (%d / %n) …',
	'[[/_admin/common/error/load]]'			=> 'Failed to load.',
	'[[/_admin/common/error/save]]'			=> 'Failed to save.',
	'[[/_admin/common/error/delete]]'		=> 'Failed to delete.',
	'[[/_admin/common/error/rename]]'		=> 'Failed to rename.',
	'[[/_admin/common/error/scan]]'			=> 'Scan failed.',
	'[[/_admin/common/error/request]]'	=> 'Request failed.',
	'[[/_admin/common/label/width]]'		=> 'Width (px)',
	'[[/_admin/common/label/height]]'		=> 'Height (px)',
	'[[/_admin/common/label/restore]]'	=> 'Restore',
	'[[/_admin/common/unit/seconds]]'		=> 'seconds',
	'[[/_admin/common/unit/decimal]]'	=> '.',
	'[[/_admin/common/msg/savedat]]'	=> 'Saved at %s.',
	'[[/_admin/common/msg/dirty]]'	=> 'Unsaved changes',
	'[[/_admin/common/error/offline]]'	=> 'No connection to the server. Check your network and try again.',
	'[[/_admin/common/hint/upload]]'	=> 'Up to %s MB and %s megapixels.',
	'[[/_admin/common/session/title]]'	=> 'Session expired',
	'[[/_admin/common/session/expired]]'	=> 'Your session has expired. Log in again – your input is kept.',
	'[[/_admin/common/session/user]]'	=> 'Email',
	'[[/_admin/common/session/pw]]'	=> 'Password',
	'[[/_admin/common/session/submit]]'	=> 'Log in',
	'[[/_admin/common/session/wrong]]'	=> 'Check your input or contact the administrator.',
	'[[/_admin/common/session/other]]'	=> 'Another account is logged in in another tab. Reload the page before you continue.',
	'[[/_admin/common/session/other_title]]'	=> 'Another account',
	'[[/_admin/common/session/reload]]'	=> 'Reload page',
	'[[/_admin/common/session/close]]'	=> 'Close',
	'[[/_admin/common/session/error]]'	=> 'The login did not work (status %s). Try again or reload the page.',
	// The error codes any panel may meet - what the server answers as 'code' (see \Nino\Http::fail()).
	// A panel's own codes carry its slug as a prefix and live in its own text/
	'[[/_admin/error/session]]'	=> 'Your session has expired.',
	'[[/_admin/error/csrf]]'	=> 'This page\'s session token is no longer valid. Reload the page.',
	'[[/_admin/error/post_too_large]]'	=> 'The request is larger than this server accepts (PHP limit for a request: %s MB).',
	'[[/_admin/error/upload_too_large]]'	=> 'The file is larger than this server accepts (PHP upload limit: %s MB).',
	'[[/_admin/error/upload_partial]]'	=> 'The file was only partly uploaded. Try again.',
	'[[/_admin/error/upload_missing]]'	=> 'No file was received.',
	'[[/_admin/error/upload_server]]'	=> 'The server could not store the upload. Check its temporary directory.',
	'[[/_admin/error/image_too_large]]'	=> 'The image is larger than %s MB.',
	'[[/_admin/error/image_type]]'	=> 'This file is not an image Nino can read. Use JPEG, PNG, WebP or GIF.',
	'[[/_admin/error/image_too_many_pixels]]'	=> 'The image has more than %s megapixels.',
	'[[/_admin/error/image_unreadable]]'	=> 'The image could not be processed. Try another file.',
	'[[/_admin/error/int_range]]'	=> 'Enter a whole number between %s and %s.',
	'[[/_admin/error/bool]]'	=> 'Choose on or off.',
	'[[/_admin/error/lines]]'	=> 'Enter one entry per line.',
	'[[/_admin/error/lines_ip]]'	=> 'Enter one IP address or CIDR range per line.',
	'[[/_admin/error/invalid_value]]'	=> 'This value is not valid.',
	'[[/_admin/error/already_top]]'	=> 'It is already at the top.',
	'[[/_admin/error/already_bottom]]'	=> 'It is already at the bottom.',
	'[[/_admin/error/wrong_password]]'	=> 'The current password is wrong.',
];
