<?php
return [
	'[[/_admin/login/label/user]]'	=> 'Email',
	'[[/_admin/login/label/pw]]'		=> 'Password',
	'[[/_admin/login/label/submit]]'=> 'Log in',

	'[[/_admin/login/error/user]]'	=> 'Email is required.',
	'[[/_admin/login/error/pw]]'		=> 'Password is required.',
	'[[/_admin/login/error/wrong]]'	=> 'Check your input or contact the administrator.',

	'[[/_admin/login/msg/welcome]]'	=> 'Enter your email and password:',
	'[[/_admin/login/msg/pending]]'	=> 'Checking your input.',

	'[[/_admin/user/logout]]'				=> 'Log out',
	'[[/_admin/user/theme]]'					=> 'Toggle light/dark',
	'[[/_admin/user/settings]]'			=> 'Settings',

	'[[/_admin/nav/dashboard]]'			=> 'Dashboard',
	'[[/_admin/nav/user]]'					=> 'User',
	'[[/_admin/nav/text]]'					=> 'Text',
	'[[/_admin/nav/images]]'				=> 'Images',
	'[[/_admin/nav/elements]]'			=> 'Elements',
	'[[/_admin/nav/submissions]]'		=> 'Submissions',
	'[[/_admin/nav/newsletter]]'		=> 'Newsletter',
	'[[/_admin/nav/logs]]'					=> 'Log',

	'[[/_admin/elements/label/type]]'			=> 'Type:',
	'[[/_admin/elements/label/add]]'				=> 'New element',
	'[[/_admin/elements/label/uri]]'				=> 'Uri',
	'[[/_admin/elements/label/uri-hint]]'	=> 'Unique string (a-z, -, _) used to identify this element, e.g. “open-workshops”.',
	'[[/_admin/elements/label/global]]'		=> 'Global',
	'[[/_admin/elements/label/yes]]'				=> 'Yes',
	'[[/_admin/elements/label/no]]'				=> 'No',
	'[[/_admin/elements/label/image-savefirst]]'	=> 'Only available after the first save.',
	'[[/_admin/elements/label/image-target]]'		=> 'Target size:',
	'[[/_admin/elements/label/locale]]'		=> 'Translation',
	'[[/_admin/elements/label/save]]'			=> 'Save',
	'[[/_admin/elements/label/delete]]'		=> 'Delete',
	'[[/_admin/elements/label/back]]'			=> 'Back to',
	'[[/_admin/elements/label/backtypes]]'	=> 'Back to overview',

	'[[/_admin/elements/msg/pending]]'			=> 'Saving …',
	'[[/_admin/elements/msg/saved]]'				=> 'Saved.',
	'[[/_admin/elements/error/uri]]'				=> 'Uri is required.',
	'[[/_admin/elements/error/save]]'			=> 'Save failed.',
	'[[/_admin/elements/error/load]]'			=> 'Failed to load.',
	'[[/_admin/elements/error/required]]'	=> 'Please fill in all required fields:',
	'[[/_admin/elements/confirm/delete]]'	=> 'Really delete this element?',

	// Multilocale field labels for the Elements form - per type + model key,
	// missing translations automatically fall back to the raw key
	'[[/_admin/elements/field/deals/title]]'					=> 'Title',
	'[[/_admin/elements/field/deals/subtitle]]'			=> 'Subtitle',
	'[[/_admin/elements/field/deals/description]]'		=> 'Description',
	'[[/_admin/elements/field/deals/price_default]]'	=> 'Default price',

	'[[/_admin/elements/field/partner/title]]'				=> 'Title',
	'[[/_admin/elements/field/partner/description]]'	=> 'Description',
	'[[/_admin/elements/field/partner/url]]'					=> 'Website',

	'[[/_admin/elements/field/portfolio/title]]'			=> 'Title',
	'[[/_admin/elements/field/portfolio/description]]'	=> 'Description',
	'[[/_admin/elements/field/portfolio/tasks]]'			=> 'Tasks',

	'[[/_admin/elements/field/pricelist/title]]'			=> 'Title',
	'[[/_admin/elements/field/pricelist/price]]'			=> 'Price',
	'[[/_admin/elements/field/pricelist/cat]]'				=> 'Category',

	'[[/_admin/elements/field/services/title]]'			=> 'Title',
	'[[/_admin/elements/field/services/subtitle]]'		=> 'Subtitle',
	'[[/_admin/elements/field/services/description]]'	=> 'Description',

	'[[/_admin/text/label/save]]'					=> 'Save',
	'[[/_admin/text/label/back]]'					=> 'Back to list',

	'[[/_admin/text/msg/pending]]'					=> 'Saving …',
	'[[/_admin/text/msg/saved]]'						=> 'Saved.',
	'[[/_admin/text/error/save]]'					=> 'Save failed.',
	'[[/_admin/text/error/load]]'					=> 'Failed to load.',

	'[[/_admin/users/label/mail]]'					=> 'Email address',
	'[[/_admin/users/label/newpw]]'				=> 'New password (leave blank to keep it unchanged)',
	'[[/_admin/users/label/currentpw]]'		=> 'Current password to confirm',
	'[[/_admin/users/label/you]]'					=> 'you',
	'[[/_admin/users/label/save]]'					=> 'Save',
	'[[/_admin/users/label/back]]'					=> 'Back to list',
	'[[/_admin/users/label/logoutall]]'		=> 'Log out everywhere',
	'[[/_admin/users/label/permissions]]'	=> 'Permissions',
	'[[/_admin/users/label/permissions-full]]' => 'Full access (every module)',
	'[[/_admin/users/label/permissions-manage]]' => 'Manage users',

	'[[/_admin/users/msg/pending]]'				=> 'Saving …',
	'[[/_admin/users/msg/saved]]'					=> 'Saved.',
	'[[/_admin/users/msg/loggedout]]'			=> 'Logged out on all devices.',
	'[[/_admin/users/error/save]]'					=> 'Save failed.',
	'[[/_admin/users/error/load]]'					=> 'Failed to load.',
	'[[/_admin/users/confirm/logoutall]]'	=> 'Really log this user out on all devices?',

	'[[/_admin/images/label/image]]'				=> 'Image',
	'[[/_admin/images/label/back]]'				=> 'Back to list',
	'[[/_admin/images/msg/pending]]'				=> 'Uploading …',
	'[[/_admin/images/msg/saved]]'					=> 'Saved.',
	'[[/_admin/images/error/save]]'				=> 'Save failed.',
	'[[/_admin/images/error/load]]'				=> 'Failed to load.',

	'[[/_admin/htmleditor/label/strong]]'	=> 'Bold',
	'[[/_admin/htmleditor/label/em]]'			=> 'Italic',
	'[[/_admin/htmleditor/label/span]]'		=> 'Highlight',
	'[[/_admin/htmleditor/label/a]]'				=> 'Link',
	'[[/_admin/htmleditor/label/linkplaceholder]]'	=> 'https://…',
	'[[/_admin/htmleditor/label/linkok]]'					=> 'Apply',
	'[[/_admin/htmleditor/label/linkcancel]]'			=> 'Cancel',
];
